local conf = {
	["filename"] = 'j-技能.xlsx',
	["sheetname"] = '客户端飘字',
	["types"] = {
'int','string','int','string','string','int'
},
	["names"] = {
'id','key','group','show','icon','delay'
},
	["data"] = {
{'1',	'AddAttrPercent_attack_up',	'',	'攻击强化',	'',	''},
{'2',	'AddAttrPercent_attack_down',	'',	'攻击弱化',	'',	''},
{'3',	'AddAttrPercent_defense_up',	'',	'防御强化',	'',	''},
{'4',	'AddAttrPercent_defense_down',	'',	'防御弱化',	'',	''},
{'5',	'AddAttr_speed_up',	'',	'机动强化',	'',	''},
{'6',	'AddAttr_speed_down',	'',	'机动弱化',	'',	''},
{'7',	'AddAttr_crit_rate_up',	'',	'暴击强化',	'',	''},
{'8',	'AddAttr_crit_rate_down',	'',	'暴击弱化',	'',	''},
{'9',	'AddAttr_crit_up',	'',	'暴伤强化',	'',	''},
{'10',	'AddAttr_crit_down',	'',	'暴伤弱化',	'',	''},
{'11',	'AddAttr_hit_up',	'',	'效果命中强化',	'',	''},
{'12',	'AddAttr_hit_down',	'',	'效果命中弱化',	'',	''},
{'13',	'AddAttr_resist_up',	'',	'效果抵抗强化',	'',	''},
{'14',	'AddAttr_resist_down',	'',	'效果抵抗弱化',	'',	''},
{'15',	'AddProgress_progress_up',	'',	'行动提前',	'',	''},
{'16',	'AddProgress_progress_down',	'',	'行动推迟',	'',	''},
{'17',	'Summon',	'',	'传送',	'',	''},
{'18',	'Unite',	'',	'同调',	'',	''},
{'19',	'AddShield',	'',	'获得护盾',	'',	''},
{'20',	'buff_hot',	'',	'持续恢复',	'',	''},
{'21',	'buff_guore',	'',	'过热',	'',	''},
{'22',	'MissBuff',	'',	'效果抵抗',	'',	''},
{'23',	'buff_weak sarcsm',	'',	'强制嘲讽',	'',	''},
{'24',	'buff_silence',	'',	'沉默',	'',	''},
{'25',	'buff_superheat',	'',	'过热',	'',	''},
{'26',	'buff_vertigo',	'',	'眩晕',	'',	''},
{'27',	'buff_freeze',	'',	'冰冻',	'',	''},
{'28',	'buff_sleeping',	'',	'昏睡',	'',	''},
{'29',	'buff_strongsarcsm',	'',	'嘲讽',	'',	''},
{'30',	'buff_guore',	'',	'过热',	'',	''},
{'31',	'buff_burn',	'',	'灼烧',	'',	''},
{'32',	'buff_woisoning',	'',	'劣化',	'',	''},
{'33',	'AddAttr_bedamage_up',	'',	'易伤',	'',	''},
{'34',	'AddAttr_bedamage_down',	'',	'减伤',	'',	''},
{'35',	'AddAttr_damage_up',	'',	'造成伤害强化',	'',	''},
{'36',	'AddAttr_damage_down',	'',	'造成伤害弱化',	'',	''},
{'37',	'AddSp',	'',	'获得同步率',	'',	''},
{'38',	'AddSp_sp_down',	'',	'减少同步率',	'',	''},
{'39',	'AddNp_up',	'',	'获得能量值',	'',	''},
{'40',	'AddNp_down',	'',	'减少能量值',	'',	''},
{'41',	'MissDamage',	'',	'化解',	'',	''},
{'42',	'buff_MissDamage',	'',	'无视单体攻击',	'',	''},
{'43',	'ImmuneBuffQuality1',	'',	'增益状态无效',	'',	''},
{'44',	'ImmuneBuffQuality2',	'',	'免疫负面状态',	'',	''},
{'45',	'ImmuneBufferGroup1',	'',	'免疫控制状态',	'',	''},
{'46',	'ImmuneBufferGroup2',	'',	'强化状态无效',	'',	''},
{'47',	'ImmuneBufferGroup3',	'',	'免疫弱化状态',	'',	''},
{'48',	'ImmuneRetreat',	'',	'免疫行动推迟',	'',	''},
{'49',	'ImmuneDamage',	'',	'相转移',	'',	''},
{'50',	'ImmuneDeath',	'',	'免疫战败退场',	'',	''},
{'51',	'buff_ImmuneBuffQuality1',	'',	'增益无效',	'',	''},
{'52',	'buff_ImmuneBuffQuality2',	'',	'负面无效',	'',	''},
{'53',	'buff_ImmuneBufferGroup1',	'',	'控制无效',	'',	''},
{'54',	'buff_ImmuneBufferGroup2',	'',	'强化无效',	'',	''},
{'55',	'buff_ImmuneBufferGroup3',	'',	'弱化无效',	'',	''},
{'56',	'buff_ImmuneRetreat',	'',	'免疫行动推迟',	'',	''},
{'57',	'buff_ImmuneDamage',	'',	'伤害免疫',	'',	''},
{'58',	'buff_ImmuneDeath',	'',	'免疫战败退场',	'',	''},
{'59',	'buff_gangdian',	'',	'麻痹',	'',	''},
{'60',	'motionless',	'',	'无法行动',	'',	''},
{'61',	'prop_1',	'',	'<color=#00FF33>恢复50%耐久</color>',	'',	''},
{'62',	'prop_2',	'',	'<color=#00FF33>恢复200耐久</color>',	'',	''},
{'63',	'prop_3',	'',	'<color=##FF3300>减少50%耐久</color>',	'',	''},
{'64',	'prop_4',	'',	'<color=##FF3300>减少200耐久</color>',	'',	''},
{'65',	'AddAttr_attack_up',	'',	'攻击强化',	'',	''},
{'66',	'AddAttr_attack_down',	'',	'攻击弱化',	'',	''},
{'67',	'AddAttr_defense_up',	'',	'防御强化',	'',	''},
{'68',	'AddAttr_defense_down',	'',	'防御弱化',	'',	''},
{'69',	'AddAttr_speed_up',	'',	'机动强化',	'',	''},
{'70',	'AddAttr_speed_down',	'',	'机动弱化',	'',	''},
{'71',	'buff_bleed',	'',	'割裂',	'',	''},
{'72',	'buff_ryzx',	'',	'属性强化',	'',	''},
{'73',	'buff_Jianliao',	'',	'修复效率弱化',	'',	''},
{'74',	'buff_guandun',	'',	'能量屏障',	'',	''},
{'75',	'buff_wudun',	'',	'物理屏障',	'',	''},
{'76',	'buff_add_type1',	'',	'扩散',	'',	''},
{'77',	'buff_add_type2',	'',	'反射',	'',	''},
{'78',	'buff_add_type3',	'',	'转移',	'',	''},
{'79',	'buff_fyNP',	'',	'能量值过载',	'',	''},
{'80',	'buff_fySP',	'',	'同步率过载',	'',	''},
{'81',	'buff_zlzj',	'',	'修复效率强化',	'',	''},
{'82',	'buff_lyzy',	'',	'能源支援',	'',	''},
{'83',	'buff_smsx',	'',	'耐久上限强化',	'',	''},
{'84',	'buff_dytz',	'',	'弹药填装',	'',	''},
{'85',	'ExtraRound',	'',	'获得额外行动',	'',	''},
{'86',	'QuShang',	'',	'效果解除',	'',	''},
{'87',	'buff_xd+1',	'',	'额外行动',	'',	''},
{'88',	'NP+20',	'',	'获得20能量值',	'',	''},
{'89',	'buff_kbzt',	'',	'进入狂暴状态',	'',	''},
{'90',	'buff_duobi',	'',	'垂化',	'',	''},
{'91',	'buff_HongWu',	'',	'磷雾',	'',	''},
{'92',	'buff_Shandie',	'',	'闪翼',	'',	''},
{'93',	'buff_XianLuo',	'',	'恐惧',	'',	''},
{'94',	'buff_synl',	'',	'能量收集',	'',	''},
{'95',	'buff_shft',	'',	'伤害反弹',	'',	''},
{'96',	'buff_jitui1',	'',	'落日熔金：威慑',	'',	''},
{'97',	'buff_xixue1',	'',	'落日熔金：吸血',	'',	''},
{'98',	'buff_qianghua1',	'',	'落日熔金：强化',	'',	''},
{'201',	'Chapter_attack_up',	'',	'<color=#00FF33>攻击强化</color>',	'',	''},
{'202',	'Chapter_attack_down',	'',	'<color=##FF3300>攻击弱化</color>',	'',	''},
{'203',	'Chapter_defense_up',	'',	'<color=#00FF33>防御强化</color>',	'',	''},
{'204',	'Chapter_defense_down',	'',	'<color=##FF3300>防御弱化</color>',	'',	''},
{'205',	'Chapter_speed_up',	'',	'<color=#00FF33>机动强化</color>',	'',	''},
{'206',	'Chapter_speed_down',	'',	'<color=##FF3300>机动弱化</color>',	'',	''},
{'207',	'Chapter_crit_rate_up',	'',	'<color=#00FF33>暴击强化</color>',	'',	''},
{'208',	'Chapter_crit_rate_down',	'',	'<color=##FF3300>暴击弱化</color>',	'',	''},
{'209',	'Chapter_crit_up',	'',	'<color=#00FF33>暴伤强化</color>',	'',	''},
{'210',	'Chapter_crit_down',	'',	'<color=##FF3300>暴伤弱化</color>',	'',	''},
{'211',	'Chapter_hit_up',	'',	'<color=#00FF33>效果命中强化</color>',	'',	''},
{'212',	'Chapter_hit_down',	'',	'<color=##FF3300>效果命中弱化</color>',	'',	''},
{'213',	'Chapter_resist_up',	'',	'<color=#00FF33>效果抵抗强化</color>',	'',	''},
{'214',	'Chapter_resist_down',	'',	'<color=##FF3300>效果抵抗弱化</color>',	'',	''},
{'215',	'Chapter_hp_up',	'',	'<color=#00FF33>HP恢复</color>',	'',	''},
{'216',	'Chapter_hp_down',	'',	'<color=##FF3300>HP减少</color>',	'',	''},
{'301',	'buff_szLjs',	'',	'受修复效果弱化',	'',	''},
{'302',	'buff_duanlu',	'',	'短路',	'',	''},
{'303',	'ReflectBuff',	'',	'反射',	'',	''},
{'304',	'buff_gaoya',	'',	'高压',	'',	''},
{'305',	'buff_wanhe',	'',	'回庇',	'',	''},
{'306',	'buff_baopojia',	'',	'爆破伤害',	'',	''},
{'307',	'buff_xuruo',	'',	'虚弱',	'',	''},
},
}
--cfgFloatFont = conf
return conf
