local conf = {
	["filename"] = 's-声音.xlsx',
	["sheetname"] = '多语言配音',
	["types"] = {
'int','string','string'
},
	["names"] = {
'id','cue_sheet','language'
},
	["data"] = {
{'1',	'Acheron',	'cn'},
{'2',	'alps',	'cn'},
{'3',	'Anthem',	'cn'},
{'4',	'Arpeggio',	'cn'},
{'5',	'Brynhild',	'cn'},
{'6',	'Burtgang',	'cn'},
{'7',	'Capriccio',	'cn'},
{'8',	'Curtana',	'cn'},
{'9',	'Direwolf',	'cn'},
{'10',	'Durandal',	'cn'},
{'11',	'Frost',	'cn'},
{'12',	'Hurricane',	'cn'},
{'13',	'Joyeuse',	'cn'},
{'14',	'Kunlun',	'cn'},
{'15',	'Lynx',	'cn'},
{'16',	'machairodus',	'cn'},
{'17',	'Megaloceros',	'cn'},
{'18',	'melody',	'cn'},
{'19',	'Meteor',	'cn'},
{'20',	'Noctilucent',	'cn'},
{'21',	'Pelorovis',	'cn'},
{'22',	'Pongo',	'cn'},
{'23',	'pyroxene',	'cn'},
{'24',	'Queen_Bee',	'cn'},
{'25',	'Rain',	'cn'},
{'26',	'Rex',	'cn'},
{'27',	'Sandfly',	'cn'},
{'28',	'syujinko_f',	'cn'},
{'29',	'syujinko_m',	'cn'},
{'30',	'Talbot',	'cn'},
{'31',	'Vortex',	'cn'},
{'32',	'wolframite',	'cn'},
{'33',	'Uillean',	'cn'},
{'34',	'Silver_Feather',	'cn'},
{'35',	'Zeus',	'cn'},
{'36',	'Lepus',	'cn'},
},
}
--cfgSoundLanguage = conf
return conf
