_G["buff_effect"]={{["uniqueness"]=false,["time"]=2000,["id"]=1,["key"]="armor"}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="weak_sarcasm",["id"]=2,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="silence",["id"]=3,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="superheat",["id"]=4,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="vertigo",["id"]=5,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=4,["key"]="freeze",["id"]=6,["play_model"]=2,["play_priority"]=3}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="sleeping",["id"]=7,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="strong_sarcasm",["id"]=8,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="burn",["id"]=9,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="poisoning",["id"]=10,["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=4,["key"]="debby_tubercle",["id"]=11,["res"]="s50180/debby_tubercle",["play_model"]=2,["play_priority"]=2}
,{["uniqueness"]=true,["play_channel"]=2,["time"]=1000,["id"]=12,["key"]="paralysis",["play_model"]=1}
,{["uniqueness"]=false,["time"]=3000,["id"]=13,["key"]="poseidon_shield"}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="bleed",["id"]=14,["play_model"]=1}
,{["id"]=15,["uniqueness"]=true,["key"]="water_ball"}
,{["uniqueness"]=true,["key"]="bomb_point",["id"]=16,["res"]="device/bomb_point"}
,{["uniqueness"]=true,["key"]="ice_point",["id"]=17,["res"]="device/ice_point"}
,{["uniqueness"]=true,["key"]="paralytic_point",["id"]=18,["res"]="device/paralytic_point"}
,{["uniqueness"]=true,["key"]="poison_point",["id"]=19,["res"]="device/poison_point"}
,{["uniqueness"]=true,["key"]="sleep_point",["id"]=20,["res"]="device/sleep_point"}
,{["uniqueness"]=true,["key"]="stun_point",["id"]=21,["res"]="device/stun_point"}
,{["uniqueness"]=true,["key"]="seckill_point",["id"]=22,["res"]="device/seckill_point"}
,{["uniqueness"]=true,["key"]="chaos_point",["id"]=23,["res"]="device/chaos_point"}
,{["uniqueness"]=true,["play_channel"]=4,["key"]="tubercle ",["id"]=24,["res"]="s50180/debby_tubercle",["play_model"]=2,["play_priority"]=2}
,{["uniqueness"]=true,["play_channel"]=4,["key"]="debby_tubercle01",["id"]=25,["res"]="s50180/debby_tubercle01",["play_model"]=2,["play_priority"]=2}
,{["uniqueness"]=true,["play_channel"]=4,["key"]="debby_shield",["id"]=26,["res"]="s50180/debby_shield",["play_model"]=2,["play_priority"]=2}
,{["uniqueness"]=false,["time"]=2000,["id"]=27,["key"]="absorb_shield"}
,{["uniqueness"]=true,["play_channel"]=2,["time"]=1500,["id"]=28,["key"]="thunder",["play_model"]=1}
,{["id"]=29,["uniqueness"]=true,["key"]="thunderTest"}
,{["uniqueness"]=true,["play_channel"]=2,["time"]=1000,["id"]=30,["key"]="paralysis_new",["play_model"]=1}
,{["uniqueness"]=false,["time"]=1500,["key"]="jarry_poison",["id"]=31,["res"]="m10190/cast1_eff2"}
,{["id"]=32,["uniqueness"]=false,["key"]="GuangDun"}
,{["id"]=33,["uniqueness"]=false,["key"]="ShitiDun"}
,{["uniqueness"]=false,["key"]="qc_buff_hit",["id"]=34,["res"]="common_hit/qc_buff_hit"}
,{["uniqueness"]=true,["play_channel"]=2,["time"]=1000,["key"]="qc_lightning_hit_strengthen",["id"]=35,["res"]="common_hit/qc_lightning_hit_strengthen",["play_model"]=1}
,{["uniqueness"]=false,["key"]="cast1_eff2",["id"]=36,["res"]="o20070/CastPassiveEff2",["attach"]="CastPassiveEffect"}
,{["uniqueness"]=false,["key"]="CastPassiveEff",["id"]=37,["res"]="o20070/CastPassiveEff",["attach"]="CastPassiveEffect"}
,{["uniqueness"]=false,["key"]="70030_cast0_hit",["id"]=38,["res"]="d70030/cast0_hit"}
,{["uniqueness"]=false,["key"]="cast1_eff_20140",["id"]=39,["res"]="o20140/cast1_eff"}
,{["uniqueness"]=false,["key"]="cast_eff_40320",["id"]=40,["res"]="a40320/cast_buff"}
,{["uniqueness"]=false,["key"]="cast3_eff_40220",["id"]=41,["res"]="a40220/cast3_eff"}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="cast3_eff3_50040",["id"]=42,["res"]="s50040/cast3_eff3",["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["time"]=1500,["key"]="cast3_hit_50040",["id"]=43,["res"]="s50040/cast3_hit",["play_model"]=1}
,{["uniqueness"]=true,["time"]=1500,["key"]="cast_buff_60030",["id"]=44,["res"]="b60030/cast_buff",["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="cast_Passive_20080",["id"]=45,["res"]="o20080/cast_Passive",["play_model"]=1}
,{["uniqueness"]=false,["key"]="Cast1Effect_01_40310",["id"]=46,["res"]="a40310/Cast1Effect_01",["attach"]="Cast1Effect_01"}
,{["uniqueness"]=false,["key"]="Cast1Effect_02_40310",["id"]=47,["res"]="a40310/Cast1Effect_02",["attach"]="Cast1Effect_02"}
,{["uniqueness"]=false,["time"]=1000,["key"]="buff_dun_70290",["id"]=48,["res"]="d70290/buff_dun"}
,{["uniqueness"]=false,["key"]="cast2_buff_92291",["id"]=49,["res"]="g92291/cast2_buff"}
,{["uniqueness"]=false,["time"]=1500,["key"]="cast_cure_60090",["id"]=50,["res"]="b60090/cast_cure"}
,{["uniqueness"]=false,["time"]=2000,["key"]="cast_debuff_60090",["id"]=51,["res"]="b60090/cast_debuff"}
,{["uniqueness"]=false,["time"]=1000,["key"]="buff_dun2_70290",["id"]=52,["res"]="d70290/buff_dun2"}
,{["uniqueness"]=false,["time"]=1500,["key"]="buff_hit_a40350",["id"]=53,["res"]="a40350/buff_hit"}
,{["uniqueness"]=false,["time"]=1500,["key"]="buff_hit_m10260",["id"]=54,["res"]="m10260/cast2buff_hit"}
,{["uniqueness"]=false,["key"]="92280_cast_hit",["id"]=55,["res"]="g92280/cast_hit"}
,{["uniqueness"]=false,["key"]="92280_cast_buff",["id"]=56,["res"]="g92280/cast_buff"}
,{["uniqueness"]=false,["time"]=1500,["key"]="93270_cast3_defend",["id"]=57,["res"]="g93270/cast3_defend"}
,{["uniqueness"]=false,["time"]=1500,["key"]="93270_cast3_defend",["id"]=58,["res"]="d70320/cast0_buff"}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="cast0_buff_70320",["id"]=59,["res"]="d70320/cast0_buff",["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["time"]=1500,["key"]="cast0_hit_70320",["id"]=60,["res"]="d70320/cast0_hit",["play_model"]=1}
,{["uniqueness"]=false,["key"]="cast2_buff_g90880",["id"]=61,["res"]="g90880/cast2_buff"}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="HightVoltage",["id"]=62,["play_model"]=1}
,{["uniqueness"]=false,["key"]="cast_buff_zhuoshao",["id"]=63,["res"]="common/cast_buff_zhuoshao"}
,{["uniqueness"]=false,["key"]="cast_buff_bingdong",["id"]=64,["res"]="common/cast_buff_bingdong"}
,{["uniqueness"]=false,["time"]=1500,["key"]="buff_hit_a40020",["id"]=65,["res"]="a40020/cast_hit"}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="Homology_eff",["id"]=66,["res"]="buff/Homology_eff",["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=2,["key"]="cast2_cure01_o20230",["id"]=67,["res"]="o20230/cast2_cure01",["play_model"]=1}
,{["uniqueness"]=true,["play_channel"]=1,["key"]="buff_eff2_o20230",["id"]=68,["res"]="o20230/buff_eff2",["play_model"]=1}
,{["uniqueness"]=false,["key"]="cast2_buff_g91060",["id"]=69,["res"]="g91060/cast_shield"}
,{["uniqueness"]=true,["key"]="cast1_buff_g91340",["id"]=70,["res"]="g91340/cast1_buff"}
,{["uniqueness"]=false,["key"]="u30500/cast_storage",["id"]=71,["res"]="u30500/cast_storage",["attach"]="CastPassiveEffect"}
}

