_G["CfgCardRoleAction"]={["furniture_sit_01"]={["action"]="坐沙发",["roleActions_m_m"]={{"walk",100}
}
,["id"]="furniture_sit_01",["roleActions_m_d"]={{"walk",100}
}
,["roleActions_g_m"]={{"walk",100}
}
,["inteDir"]=false,["roleActions_g_d"]={{"walk",100}
}
,["loop"]={7,12}
,["key"]="furniture_sit_01",["sType"]="furniture",["restore"]=2,["actionTalkID2"]=6}
,["base_dozeOff"]={["action"]="打瞌睡",["id"]="base_dozeOff",["roleActions_g_m"]={{"walk",20}
,{"idle",100}
}
,["inteDir"]=false,["loop"]={8,13}
,["key"]="base_dozeOff",["sType"]="leisure",["roleActions_g_d"]={{"walk",50}
,{"idle",50}
,{"normal_stretch",50}
}
,["restore"]=5}
,["furniture_sit_03"]={["action"]="坐睡（左）",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["id"]="furniture_sit_03",["key"]="furniture_sit_03",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=false,["roleActions_g_d"]={{"walk",100}
}
,["loop"]={16,21}
,["actionTalkID3"]=9,["faceName"]="furniture_sit_03",["sType"]="furniture",["restore"]=5,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_watch"]={["action"]="观看",["id"]="furniture_watch",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={7}
,["key"]="furniture_watch",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["click_grab"]={["shadow"]=1,["action"]="抓起",["id"]="click_grab",["roleActions_g_m"]={{"idle",100}
,{"walk",50}
}
,["inteDir"]=false,["key"]="click_grab",["roleActions_m_m"]={{"idle",100}
,{"walk",50}
}
,["sType"]="grab",["roleActions_g_d"]={{"idle",100}
}
,["robotActions"]={{"idle",50}
,{"walk",50}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",50}
}
}
,["furniture_wangyuanjing01"]={["action"]="望远镜",["id"]="furniture_wangyuanjing01",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={3}
,["key"]="furniture_wangyuanjing01",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_sleep_02"]={["shadow"]=1,["action"]="睡觉2（从右边上床）",["id"]="furniture_sleep_02",["roleActions_g_m"]={{"walk",100}
}
,["inteDir"]=false,["roleActions_m_m"]={{"walk",100}
}
,["loop"]={14,24}
,["key"]="furniture_sleep_02",["roleActions_g_d"]={{"walk",100}
}
,["sType"]="furniture",["faceName"]="furniture_sleep_02",["restore"]=10,["roleActions_m_d"]={{"walk",100}
}
}
,["furniture_Nod"]={["action"]="点头",["id"]="furniture_Nod",["roleActions_g_m"]={{"walk",50}
,{"idle",100}
,{"base_dozeOff",100}
}
,["inteDir"]=false,["loop"]={2}
,["key"]="furniture_Nod",["roleActions_m_m"]={{"walk",50}
,{"idle",100}
}
,["sType"]="leisure",["roleActions_g_d"]={{"idle",100}
}
,["robotActions"]={{"idle",50}
,{"walk",50}
}
,["roleActions_m_d"]={{"walk",50}
,{"idle",100}
}
}
,["normal_daze_05"]={["loop"]={7}
,["roleActions_g_d"]={{"normal_daze_03",50}
,{"normal_daze_04",50}
,{"walk",50}
}
,["action"]="热身（女）",["sType"]="leisure",["id"]="normal_daze_05",["key"]="normal_daze_05",["inteDir"]=false}
,["furniture_Dance"]={["shadow"]=1,["action"]="跳舞",["id"]="furniture_Dance",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={11}
,["key"]="furniture_Dance",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["normal_daze_04"]={["loop"]={9}
,["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
,["action"]="舞蹈-活泼（女）",["sType"]="leisure",["id"]="normal_daze_04",["key"]="normal_daze_04",["inteDir"]=false}
,["furniture_sleep_01"]={["shadow"]=1,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_g_m"]={{"walk",100}
}
,["actionTalkID3"]=5,["centerOffset"]={1,0,-1}
,["restore"]=10,["roleActions_m_d"]={{"walk",100}
}
,["id"]="furniture_sleep_01",["actionTalkID1"]=3,["inteDir"]=false,["loop"]={14,24}
,["roleActions_m_m"]={{"walk",100}
}
,["action"]="睡觉1（从左边上床）",["sType"]="furniture",["faceName"]="furniture_sleep_01",["key"]="furniture_sleep_01",["actionTalkID2"]=4}
,["role_highfive_01"]={["roleActions_g_d"]={{"walk",100}
}
,["id"]="role_highfive_01",["inteDir"]=false,["loop"]={3}
,["key"]="role_highfive_01",["sType"]="furniture",["action"]="击掌-右手",["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_chuanduo01"]={["action"]="船舵",["id"]="furniture_chuanduo01",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={3}
,["key"]="furniture_chuanduo01",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_piano"]={["action"]="钢琴",["id"]="furniture_piano",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={6}
,["key"]="furniture_piano",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["normal_clean"]={["action"]="打扫",["id"]="normal_clean",["actionTalkID1"]=2,["inteDir"]=false,["childs"]={"Prop/Furn_ComA_Broom_01"}
,["loop"]={13}
,["key"]="normal_clean",["sType"]="leisure",["roleActions_g_d"]={{"idle",50}
,{"normal_stretch",50}
,{"normal_fatigue",50}
,{"walk",50}
}
}
,["normal_daze_01"]={["loop"]={5,15}
,["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
,["action"]="思考",["sType"]="leisure",["id"]="normal_daze_01",["key"]="normal_daze_01",["inteDir"]=false}
,["furniture_revive01"]={["shadow"]=1,["action"]="棺材",["id"]="furniture_revive01",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={9}
,["key"]="furniture_revive01",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["role_highfive_02"]={["roleActions_g_d"]={{"walk",100}
}
,["id"]="role_highfive_02",["inteDir"]=false,["loop"]={3}
,["key"]="role_highfive_02",["sType"]="furniture",["action"]="击掌-左手",["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_sit_02"]={["action"]="坐椅子（看书）",["roleActions_m_m"]={{"walk",100}
}
,["id"]="furniture_sit_02",["roleActions_m_d"]={{"walk",100}
}
,["actionTalkID1"]=7,["inteDir"]=false,["roleActions_g_m"]={{"walk",100}
}
,["loop"]={13}
,["key"]="furniture_sit_02",["roleActions_g_d"]={{"walk",100}
}
,["sType"]="furniture",["childs"]={"Prop/Furn_ComA_Book_01"}
,["actionTalkID2"]=8}
,["furniture_lordsit"]={["shadow"]=1,["action"]="王座",["id"]="furniture_lordsit",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=false,["loop"]={12}
,["key"]="furniture_lordsit",["sType"]="furniture",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["base_handlingData"]={["action"]="送货（基建）",["id"]="base_handlingData",["roleActions_g_m"]={{"walk",20}
,{"idle",100}
}
,["inteDir"]=false,["loop"]={6,11}
,["key"]="base_handlingData",["sType"]="leisure",["roleActions_m_m"]={{"walk",20}
,{"idle",100}
}
,["childs"]={"Prop/Furn_ComA_UAV_01","Prop/Furn_ComA_CargoBox_0"}
}
,["base_operatePC1"]={["roleActions_g_d"]={{"walk",20}
,{"idle",100}
}
,["id"]="base_operatePC1",["inteDir"]=true,["loop"]={5}
,["key"]="base_operatePC1",["sType"]="furniture",["action"]="操作电脑（基建）",["roleActions_m_d"]={{"walk",20}
,{"idle",100}
}
}
,["base_operatePC"]={["roleActions_m_m"]={{"walk",20}
,{"idle",100}
}
,["loop"]={5}
,["action"]="操作电脑（基建）",["key"]="base_operatePC",["sType"]="furniture",["id"]="base_operatePC",["roleActions_g_m"]={{"walk",20}
,{"idle",100}
}
,["inteDir"]=true}
,["furniture_sit_04"]={["action"]="坐有靠背的椅子",["id"]="furniture_sit_04",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=false,["loop"]={8}
,["key"]="furniture_sit_04",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["sType"]="furniture",["roleActions_g_d"]={{"walk",100}
}
,["restore"]=2,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_Watering"]={["childs"]={"Prop/Furn_ComA_WateringPot"}
,["id"]="furniture_Watering",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={6}
,["key"]="furniture_Watering",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["sType"]="furniture",["action"]="浇水",["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["base_drinkTea"]={["childs"]={"Prop/base_drinkTea"}
,["id"]="base_drinkTea",["roleActions_g_m"]={{"walk",20}
,{"idle",100}
}
,["inteDir"]=false,["loop"]={8}
,["key"]="base_drinkTea",["sType"]="leisure",["action"]="喝茶",["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
}
,["idle"]={["action"]="悠闲",["id"]="idle",["roleActions_g_m"]={{"walk",50}
,{"Furn_ComA_ipad_01",50}
,{"base_dozeOff",20}
,{"base_drinkTea",50}
,{"base_phone",50}
,{"base_handlingData",50}
}
,["inteDir"]=false,["loop"]={2,8}
,["key"]="idle",["roleActions_m_m"]={{"walk",50}
,{"Furn_ComA_ipad_01",50}
,{"base_phone",50}
}
,["sType"]="Speed",["roleActions_g_d"]={{"walk",150}
,{"Furn_ComA_ipad_01",10}
,{"base_dozeOff",10}
,{"base_drinkTea",10}
,{"base_phone",10}
,{"normal_clean",5}
,{"normal_daze_0",10}
,{"normal_daze_06",10}
}
,["robotActions"]={{"walk",100}
}
,["roleActions_m_d"]={{"walk",50}
,{"Furn_ComA_ipad_01",50}
,{"base_phone",50}
}
}
,["normal_stretch"]={["loop"]={5}
,["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
,["action"]="伸懒腰",["sType"]="leisure",["id"]="normal_stretch",["key"]="normal_stretch",["inteDir"]=false}
,["normal_daze_06"]={["childs"]={"Prop/Furn_ComA_Book_02"}
,["id"]="normal_daze_06",["inteDir"]=false,["loop"]={15}
,["key"]="normal_daze_06",["sType"]="leisure",["action"]="看书（女）",["roleActions_g_d"]={{"walk",50}
,{"idle",50}
,{"normal_stretch",50}
}
}
,["normal_daze_03"]={["loop"]={11}
,["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
,["action"]="舞蹈-可爱（女）",["sType"]="leisure",["id"]="normal_daze_03",["key"]="normal_daze_03",["inteDir"]=false}
,["click_lens"]={["action"]="望向镜头",["id"]="click_lens",["roleActions_g_m"]={{"walk",50}
,{"idle",100}
,{"base_dozeOff",100}
}
,["inteDir"]=false,["loop"]={4}
,["key"]="click_lens",["roleActions_m_m"]={{"walk",50}
,{"idle",100}
}
,["sType"]="leisure",["roleActions_g_d"]={{"idle",100}
}
,["robotActions"]={{"idle",50}
,{"walk",50}
}
,["roleActions_m_d"]={{"walk",50}
,{"idle",100}
}
}
,["furniture_sit_05"]={["action"]="坐无靠背的椅子",["id"]="furniture_sit_05",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=false,["childs"]={"Prop/Furn_ComA_Switch_01"}
,["loop"]={12}
,["key"]="furniture_sit_05",["roleActions_g_d"]={{"walk",100}
}
,["sType"]="furniture",["restore"]=3,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["furniture_gundam"]={["childs"]={"Prop/Furn_ComA_Model_01"}
,["id"]="furniture_gundam",["roleActions_g_m"]={{"idle",100}
,{"walk",100}
}
,["inteDir"]=true,["loop"]={13}
,["key"]="furniture_gundam",["roleActions_m_m"]={{"idle",100}
,{"walk",100}
}
,["sType"]="furniture",["action"]="玩模型",["roleActions_g_d"]={{"walk",100}
}
,["roleActions_m_d"]={{"idle",100}
,{"walk",100}
}
}
,["normal_fatigue"]={["action"]="疲劳",["id"]="normal_fatigue",["actionTalkID1"]=1,["inteDir"]=false,["loop"]={10}
,["key"]="normal_fatigue",["sType"]="leisure",["roleActions_g_d"]={{"idle",50}
,{"base_dozeOff",50}
}
}
,["base_phone"]={["childs"]={"Prop/base_phone"}
,["id"]="base_phone",["roleActions_g_m"]={{"walk",20}
,{"idle",100}
}
,["inteDir"]=false,["loop"]={8}
,["key"]="base_phone",["roleActions_m_m"]={{"walk",20}
,{"idle",100}
}
,["sType"]="leisure",["action"]="打电话",["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
,["roleActions_m_d"]={{"walk",20}
,{"idle",100}
}
}
,["Furn_ComA_ipad_01"]={["childs"]={"Prop/Furn_ComA_ipad_01"}
,["id"]="Furn_ComA_ipad_01",["roleActions_g_m"]={{"walk",20}
,{"idle",100}
}
,["inteDir"]=false,["loop"]={5}
,["key"]="Furn_ComA_ipad_01",["roleActions_m_m"]={{"walk",20}
,{"idle",100}
}
,["sType"]="leisure",["action"]="看ipad",["roleActions_g_d"]={{"walk",50}
,{"idle",50}
}
,["roleActions_m_d"]={{"walk",20}
,{"idle",100}
}
}
,["click_lens_02"]={["action"]="望向镜头2（内敛）",["id"]="click_lens_02",["roleActions_g_m"]={{"walk",50}
,{"idle",100}
,{"base_dozeOff",100}
}
,["inteDir"]=false,["loop"]={4}
,["key"]="click_lens_02",["roleActions_m_m"]={{"walk",50}
,{"idle",100}
}
,["sType"]="leisure",["roleActions_g_d"]={{"idle",100}
}
,["robotActions"]={{"idle",50}
,{"walk",50}
}
,["roleActions_m_d"]={{"walk",50}
,{"idle",100}
}
}
,["walk"]={["action"]="移动",["id"]="walk",["roleActions_g_m"]={{"idle",50}
,{"Furn_ComA_ipad_01",50}
,{"base_dozeOff",50}
,{"base_drinkTea",10}
,{"base_phone",10}
}
,["inteDir"]=false,["key"]="walk",["roleActions_m_m"]={{"idle",50}
,{"Furn_ComA_ipad_01",50}
,{"base_phone",10}
}
,["sType"]="Speed",["roleActions_g_d"]={{"idle",100}
}
,["robotActions"]={{"idle",100}
}
,["roleActions_m_d"]={{"idle",50}
,{"Furn_ComA_ipad_01",50}
,{"base_phone",10}
}
}
}

