local conf = {
	["filename"] = 't-图鉴表.xlsx',
	["sheetname"] = '多人插画',
	["types"] = {
'int','string','string','string','table#4','int','int','string','int'
},
	["names"] = {
'id','key','small','name','infos','index','board_id','icon','shopId'
},
	["data"] = {
{'1',	'1',	'arch_seashore',	'海边度假',	'',	'',	'',	'',	''},
{'1',	'1',	'',	'',	'',	'1',	'2',	'arch_seashore',	'80401'},
{'1',	'1',	'',	'',	'',	'2',	'4',	'arch_summer_rendezvous',	'80402'},
{'1',	'1',	'',	'',	'',	'3',	'23',	'arch_summer_swimming_party',	''},
{'1',	'1',	'',	'',	'',	'4',	'24',	'arch_beach_holidays',	'80415'},
{'1',	'1',	'',	'',	'',	'5',	'25',	'arch_cool_bright_summer',	'80416'},
{'1',	'1',	'',	'',	'',	'6',	'26',	'arch_warm_summer',	'80417'},
{'1',	'1',	'',	'',	'',	'7',	'28',	'arch_coolness_of_summer',	''},
{'2',	'2',	'arch_three_people',	'宿舍故事',	'',	'',	'',	'',	''},
{'2',	'2',	'',	'',	'',	'1',	'1',	'arch_three_people',	''},
{'2',	'2',	'',	'',	'',	'2',	'3',	'arch_kadya_liedown',	''},
{'2',	'2',	'',	'',	'',	'3',	'7',	'arch_trytomoveforward',	'80405'},
{'2',	'2',	'',	'',	'',	'4',	'9',	'arch_play_time',	''},
{'2',	'2',	'',	'',	'',	'5',	'10',	'arch_relaxing_afternoon',	''},
{'2',	'2',	'',	'',	'',	'6',	'13',	'arch_greenhouse',	'80407'},
{'2',	'2',	'',	'',	'',	'7',	'14',	'arch_starry_night',	'80408'},
{'2',	'2',	'',	'',	'',	'9',	'15',	'arch_fun_with_mew',	''},
{'2',	'2',	'',	'',	'',	'8',	'16',	'arch_tender_dream',	'80409'},
{'2',	'2',	'',	'',	'',	'9',	'17',	'arch_intoxicated_shadow',	'80410'},
{'2',	'2',	'',	'',	'',	'10',	'18',	'arch_weightless_space',	'80411'},
{'3',	'3',	'arch_shimmering_feast',	'佳节逐禧',	'',	'',	'',	'',	''},
{'3',	'3',	'',	'',	'',	'1',	'5',	'arch_shimmering_feast',	'80403'},
{'3',	'3',	'',	'',	'',	'2',	'6',	'arch_fireworks_IoIent',	'80404'},
{'3',	'3',	'',	'',	'',	'3',	'19',	'arch_moonlight_sharing',	'80413'},
{'3',	'3',	'',	'',	'',	'4',	'30',	'arch_starry_lotus_fire',	''},
{'4',	'4',	'arch_base_check',	'作战准备',	'',	'',	'',	'',	''},
{'4',	'4',	'',	'',	'',	'1',	'8',	'arch_base_check',	''},
{'5',	'5',	'arch_bestie_agent',	'娇痴颐使',	'',	'',	'',	'',	''},
{'5',	'5',	'',	'',	'',	'1',	'11',	'arch_bestie_agent',	'80406'},
{'6',	'6',	'arch_trip_in_the_milky_way',	'寰宇梦境',	'',	'',	'',	'',	''},
{'6',	'6',	'',	'',	'',	'1',	'12',	'arch_trip_in_the_milky_way',	''},
{'6',	'6',	'',	'',	'',	'2',	'20',	'arch_guard_of_iron_bastion',	'80412'},
{'6',	'6',	'',	'',	'',	'3',	'21',	'arch_silhouette_in_a_moment',	''},
{'6',	'6',	'',	'',	'',	'4',	'22',	'arch_snowland_gods',	''},
{'6',	'6',	'',	'',	'',	'5',	'31',	'arch_sign_of_mutation',	''},
{'6',	'6',	'',	'',	'',	'6',	'32',	'arch_waves_tumble',	''},
{'6',	'6',	'',	'',	'',	'7',	'33',	'arch_rainbow_in_the_sky',	''},
{'6',	'6',	'',	'',	'',	'8',	'35',	'arch_person_on_the_darknet',	''},
{'6',	'6',	'',	'',	'',	'9',	'36',	'arch_rebuilding_together',	''},
{'6',	'6',	'',	'',	'',	'10',	'40',	'arch_a_narrow_escape',	''},
{'7',	'7',	'arch_dance_for_joy',	'涂色速写',	'',	'',	'',	'',	''},
{'7',	'7',	'',	'',	'',	'1',	'27',	'arch_dance_for_joy',	''},
{'8',	'8',	'arch_camping_with_fireworks',	'闲适假日',	'',	'',	'',	'',	''},
{'8',	'8',	'',	'',	'',	'1',	'29',	'arch_camping_with_fireworks',	'80418'},
{'9',	'9',	'arch_law_of_the_streets',	'都市掠影',	'',	'',	'',	'',	''},
{'9',	'9',	'',	'',	'',	'1',	'39',	'arch_law_of_the_streets',	'80419'},
},
}
--cfgCfgArchiveIllustration = conf
return conf
