_G["CfgDySetOpenCfgs"]={["CfgActiveEntry"]={["id"]="CfgActiveEntry",["fields"]={{["index"]=1,["field_type"]="number",["desc"]="是否在主界面显示",["field"]="mainShow"}
,{["index"]=2,["field_type"]="string",["desc"]="开始时间",["field"]="begTime"}
,{["index"]=3,["field_type"]="string",["desc"]="困难本开启时间",["field"]="hardBegTime"}
,{["index"]=4,["field_type"]="string",["desc"]="副本关闭时间",["field"]="battleendTime"}
,{["index"]=5,["field_type"]="string",["desc"]="结束时间",["field"]="endTime"}
}
,["name"]="Active",["sheetName"]="活动表"}
,["global_setting"]={["id"]="global_setting",["fields"]={{["index"]=1,["show_ids"]={"g_ZilongWebBtnOpen","g_ZilongWebBtnClose","g_ZilongWebBtnLv"}
,["field_type"]="string",["desc"]="活动按钮开启",["field"]="value"}
}
,["sheetName"]="表"}
,["CfgCommodity"]={["id"]="CfgCommodity",["fields"]={{["index"]=1,["field_type"]="string",["desc"]="购买开始时间",["field"]="sBuyStart"}
,{["index"]=2,["field_type"]="string",["desc"]="购买结束时间",["field"]="sBuyEnd"}
}
,["name"]="CfgCommodity",["sheetName"]="固定商品配置"}
,["CfgActiveList"]={["id"]="CfgActiveList",["fields"]={{["index"]=1,["field_type"]="string",["desc"]="开始时间",["field"]="sTime"}
,{["index"]=2,["field_type"]="string",["desc"]="结束时间",["field"]="eTime"}
}
,["name"]="CfgActiveList",["sheetName"]="活动列表"}
,["CfgCardPool"]={["id"]="CfgCardPool",["fields"]={{["index"]=1,["field_type"]="date",["desc"]="开始时间",["field"]="sStart"}
,{["index"]=2,["field_type"]="date",["desc"]="结束时间",["field"]="sEnd"}
,{["index"]=3,["field_type"]="json",["desc"]="抽卡花费",["field"]="jCost"}
}
,["name"]="CardPool",["sheetName"]="卡池配置表"}
,["ItemInfo"]={["id"]="ItemInfo",["fields"]={{["index"]=1,["field_type"]="string",["desc"]="失效日期",["field"]="sExpiry"}
,{["index"]=2,["field_type"]="number",["desc"]="失效序列值",["field"]="expiryIx"}
}
,["name"]="ItemInfo",["sheetName"]="ItemInfo"}
,["CfgAccTypeLimit"]={["id"]="CfgAccTypeLimit",["fields"]={{["index"]=1,["desc"]="在线总时长",["sub_index_type"]="number",["field_type"]="number",["sub_tb"]="infos",["field"]="sumTime"}
}
,["name"]="name",["sheetName"]="账号限制"}
,["AvatarFrame"]={["id"]="AvatarFrame",["fields"]={{["index"]=1,["field_type"]="bool",["desc"]="是否显示",["field"]="isShow"}
,{["index"]=2,["field_type"]="number",["desc"]="类型",["field"]="type"}
}
,["name"]="avatarname",["sheetName"]="头像框"}
,["CfgAvatar"]={["id"]="CfgAvatar",["fields"]={{["index"]=1,["field_type"]="bool",["desc"]="是否显示在列表中",["field"]="isShow"}
}
,["name"]="avatarname",["sheetName"]="头像"}
}

