_G["cfgColosseumOptional"]={{["id"]=1,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=101,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="1"}
,{["id"]=2,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=101,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="2"}
,{["id"]=3,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=102,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="3"}
,{["id"]=4,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=102,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="4"}
,{["id"]=5,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=102,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="5"}
,{["id"]=6,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=102,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="6"}
,{["id"]=7,["infos"]={{["maxTurn"]=9,["modeId"]=1,["teamSet"]=0}
,{["maxTurn"]=9,["modeId"]=2,["charaGachaId"]=102,["reChooseTurn"]={4,6}
,["nChoose"]=3,["turnNum"]=6,["teamSet"]=1}
}
,["key"]="7"}
}

