_G["cfgQuestionsGroup"]={{["infos"]={{["answer"]="月亮",["index"]=1,["isright"]=1}
,{["answer"]="太阳",["index"]=2}
,{["answer"]="北极星",["index"]=3}
,{["answer"]="流星",["index"]=4}
,{["answer"]="金星",["index"]=5}
,{["answer"]="木星",["index"]=6}
}
,["key"]=1,["question"]="一面镜子亮晶晶，走遍天下照古今。十五十六最圆满，千家万户仰头寻。 (打一自然天体)",["id"]=1,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="农历八月十五",["index"]=1,["isright"]=1}
,{["answer"]="农历五月十五",["index"]=2}
,{["answer"]="农历六月十五",["index"]=3}
,{["answer"]="农历七月十五",["index"]=4}
,{["answer"]="农历九月十五",["index"]=5}
,{["answer"]="农历十月十五",["index"]=6}
}
,["key"]=2,["question"]="由上古时代秋夕祭月演变而来的中秋节，时间为？",["id"]=2,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="后羿射日",["index"]=1,["isright"]=1}
,{["answer"]="嫦娥奔月",["index"]=2}
,{["answer"]="吴刚伐桂",["index"]=3}
,{["answer"]="玉兔捣药",["index"]=4}
,{["answer"]="‌月饼起义",["index"]=5}
,{["answer"]="玄宗游月",["index"]=6}
}
,["key"]=3,["question"]="以下哪个传说与中秋节无关？",["id"]=3,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="端午节",["index"]=1,["isright"]=1}
,{["answer"]="祭月节",["index"]=2}
,{["answer"]="月光诞",["index"]=3}
,{["answer"]="拜月节",["index"]=4}
,{["answer"]="团圆节",["index"]=5}
,{["answer"]="仲秋节",["index"]=6}
}
,["key"]=4,["question"]="以下哪个不是中秋节的别称？",["id"]=4,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="桂花",["index"]=1,["isright"]=1}
,{["answer"]="牡丹",["index"]=2}
,{["answer"]="郁金香",["index"]=3}
,{["answer"]="百合",["index"]=4}
,{["answer"]="玫瑰",["index"]=5}
,{["answer"]="牵牛花",["index"]=6}
}
,["key"]=5,["question"]="金灿灿，银灿灿，小小花儿真漂亮，秋风一吹喷喷香，你家我家万家香。 (打一植物)",["id"]=5,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="明",["index"]=1,["isright"]=1}
,{["answer"]="玩",["index"]=2}
,{["answer"]="晶",["index"]=3}
,{["answer"]="朋",["index"]=4}
,{["answer"]="旦",["index"]=5}
,{["answer"]="昌",["index"]=6}
}
,["key"]=6,["question"]="太阳西边下，月亮东边挂。（打一个字）",["id"]=6,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="儿童节",["index"]=1,["isright"]=1}
,{["answer"]="春节",["index"]=2}
,{["answer"]="中秋节",["index"]=3}
,{["answer"]="端午节",["index"]=4}
,{["answer"]="清明节",["index"]=5}
}
,["key"]=7,["question"]="以下哪个节日不是四大传统节日？",["id"]=7,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="划龙舟",["index"]=1,["isright"]=1}
,{["answer"]="吃月饼",["index"]=2}
,{["answer"]="猜灯谜",["index"]=3}
,{["answer"]="玩花灯",["index"]=4}
,{["answer"]="赏月",["index"]=5}
,{["answer"]="赏桂花",["index"]=6}
}
,["key"]=8,["question"]="以下哪个活动不是中秋节常见活动？",["id"]=8,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="玉兔号",["index"]=1,["isright"]=1}
,{["answer"]="金狮号",["index"]=2}
,{["answer"]="白虎号",["index"]=3}
,{["answer"]="企鹅号",["index"]=4}
,{["answer"]="山羊号",["index"]=5}
,{["answer"]="骏马号",["index"]=6}
}
,["key"]=9,["question"]="月球车被描述为在月球上孤独奋斗的象征，它在没有人类陪伴的情况下，独自完成了长达两年半的月球探测任务，那么它的名字是？",["id"]=9,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="月饼",["index"]=1,["isright"]=1}
,{["answer"]="年糕",["index"]=2}
,{["answer"]="糖葫芦",["index"]=3}
,{["answer"]="粽子",["index"]=4}
,{["answer"]="元宵",["index"]=5}
,{["answer"]="青团",["index"]=6}
}
,["key"]=10,["question"]="在此佳节，队员们邀请总队长一同赏月，带来了以下哪个应节食品？",["id"]=10,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="构建蓝图",["index"]=1,["isright"]=1}
,{["answer"]="荧晶密钥",["index"]=2}
,{["answer"]="演习勋章",["index"]=3}
,{["answer"]="进化之息",["index"]=4}
,{["answer"]="涅槃精华",["index"]=5}
,{["answer"]="家园币",["index"]=6}
}
,["key"]=11,["question"]="以下哪个道具可以用于核心构建？",["id"]=11,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="燃料",["index"]=1,["isright"]=1}
,{["answer"]="涅槃剂",["index"]=2}
,{["answer"]="亚金沙",["index"]=3}
,{["answer"]="星币",["index"]=4}
,{["answer"]="微晶",["index"]=5}
,{["answer"]="技术点",["index"]=6}
}
,["key"]=12,["question"]="当以下哪项资源不足的时候，总队长无法主动出击主线剧情？",["id"]=12,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="核心跃升",["index"]=1,["isright"]=1}
,{["answer"]="加好感度",["index"]=2}
,{["answer"]="设施升级",["index"]=3}
,{["answer"]="入住宿舍",["index"]=4}
,{["answer"]="技能升级",["index"]=5}
,{["answer"]="分解芯片",["index"]=6}
}
,["key"]=13,["question"]="进行以下哪项操作后，可以解锁队员的等级上限？",["id"]=13,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="C.C.C.",["index"]=1,["isright"]=1}
,{["answer"]="阿尔卑斯",["index"]=2}
,{["answer"]="飓风",["index"]=3}
,{["answer"]="刃齿",["index"]=4}
,{["answer"]="女王蜂",["index"]=5}
}
,["key"]=14,["question"]="以下哪位队员不是探索队分队的队长？",["id"]=14,["answerIndex"]=1,["group"]=1,["weight"]=100}
,{["infos"]={{["answer"]="女王蜂",["index"]=1,["isright"]=1}
,{["answer"]="星坠",["index"]=2}
,{["answer"]="飓风",["index"]=3}
,{["answer"]="寒霜",["index"]=4}
,{["answer"]="雷暴",["index"]=5}
,{["answer"]="霞光",["index"]=6}
}
,["key"]=15,["question"]="以下哪位队员不属于“气象”小队？",["id"]=15,["answerIndex"]=1,["group"]=1,["weight"]=100}
}

