_G["CfgBuilding"]={[1002]={["infos"]={{["index"]=1,["modelName"]="heneng01"}
,{["index"]=2,["modelName"]="heneng01"}
,{["index"]=3,["modelName"]="heneng01"}
,{["index"]=4,["modelName"]="heneng02"}
,{["index"]=5,["modelName"]="heneng02"}
,{["index"]=6,["modelName"]="heneng02"}
,{["index"]=7,["modelName"]="heneng02"}
,{["index"]=8,["modelName"]="heneng03"}
,{["index"]=9,["modelName"]="heneng03"}
,{["index"]=10,["modelName"]="heneng03"}
}
,["key"]="1002",["modelScale"]=4,["angle"]=0,["id"]=1002,["namePos"]={0,0,0}
}
,[1004]={["infos"]={{["index"]=1,["modelName"]="cuiqu01"}
,{["index"]=2,["modelName"]="cuiqu01"}
,{["index"]=3,["modelName"]="cuiqu01"}
,{["index"]=4,["modelName"]="cuiqu02"}
,{["index"]=5,["modelName"]="cuiqu02"}
,{["index"]=6,["modelName"]="cuiqu02"}
,{["index"]=7,["modelName"]="cuiqu02"}
,{["index"]=8,["modelName"]="cuiqu03"}
,{["index"]=9,["modelName"]="cuiqu03"}
,{["index"]=10,["modelName"]="cuiqu03"}
}
,["key"]="1004",["modelScale"]=4,["angle"]=0,["id"]=1004,["namePos"]={0,0,0}
}
,[1006]={["infos"]={{["index"]=1,["modelName"]="yanjiu01"}
,{["index"]=2,["modelName"]="yanjiu01"}
,{["index"]=3,["modelName"]="yanjiu01"}
,{["index"]=4,["modelName"]="yanjiu02"}
,{["index"]=5,["modelName"]="yanjiu02"}
,{["index"]=6,["modelName"]="yanjiu02"}
,{["index"]=7,["modelName"]="yanjiu02"}
,{["index"]=8,["modelName"]="yanjiu03"}
,{["index"]=9,["modelName"]="yanjiu03"}
,{["index"]=10,["modelName"]="yanjiu03"}
}
,["key"]="1006",["modelScale"]=4,["angle"]=0,["id"]=1006,["namePos"]={0,0,0}
}
,[1008]={["infos"]={{["index"]=1,["modelName"]="yingji01_2"}
,{["index"]=2,["modelName"]="yingji01_2"}
,{["index"]=3,["modelName"]="yingji01_2"}
,{["index"]=4,["modelName"]="yingji01_2"}
,{["index"]=5,["modelName"]="yingji01_2"}
,{["index"]=6,["modelName"]="yingji01_2"}
,{["index"]=7,["modelName"]="yingji01_2"}
,{["index"]=8,["modelName"]="yingji01_2"}
,{["index"]=9,["modelName"]="yingji01_2"}
,{["index"]=10,["modelName"]="yingji01_2"}
}
,["key"]="1008",["modelScale"]=3,["angle"]=0,["id"]=1008,["namePos"]={0,0,0}
}
,[2001]={["infos"]={{["index"]=1,["modelName"]="xunlian01"}
,{["index"]=2,["modelName"]="xunlian01"}
,{["index"]=3,["modelName"]="xunlian01"}
,{["index"]=4,["modelName"]="xunlian02"}
,{["index"]=5,["modelName"]="xunlian02"}
,{["index"]=6,["modelName"]="xunlian02"}
,{["index"]=7,["modelName"]="xunlian02"}
,{["index"]=8,["modelName"]="xunlian03"}
,{["index"]=9,["modelName"]="xunlian03"}
,{["index"]=10,["modelName"]="xunlian03"}
}
,["key"]="2001",["modelScale"]=3,["angle"]=0,["id"]=2001,["namePos"]={0,0,0}
}
,[1001]={["infos"]={{["index"]=1,["modelName"]="zhihui01"}
,{["index"]=2,["modelName"]="zhihui01"}
,{["index"]=3,["modelName"]="zhihui01"}
,{["index"]=4,["modelName"]="zhihui02"}
,{["index"]=5,["modelName"]="zhihui02"}
,{["index"]=6,["modelName"]="zhihui02"}
,{["index"]=7,["modelName"]="zhihui02"}
,{["index"]=8,["modelName"]="zhihui03"}
,{["index"]=9,["modelName"]="zhihui03"}
,{["index"]=10,["modelName"]="zhihui03"}
}
,["key"]="1001",["modelScale"]=5,["angle"]=0,["id"]=1001,["namePos"]={0,0,0}
}
,[1003]={["infos"]={{["index"]=1,["modelName"]="buji01"}
,{["index"]=2,["modelName"]="buji01"}
,{["index"]=3,["modelName"]="buji01"}
,{["index"]=4,["modelName"]="buji02"}
,{["index"]=5,["modelName"]="buji02"}
,{["index"]=6,["modelName"]="buji02"}
,{["index"]=7,["modelName"]="buji02"}
,{["index"]=8,["modelName"]="buji03"}
,{["index"]=9,["modelName"]="buji03"}
,{["index"]=10,["modelName"]="buji03"}
}
,["key"]="1003",["modelScale"]=4,["angle"]=0,["id"]=1003,["namePos"]={0,0,0}
}
,[1005]={["infos"]={{["index"]=1,["modelName"]="guidao01"}
,{["index"]=2,["modelName"]="guidao01"}
,{["index"]=3,["modelName"]="guidao01"}
,{["index"]=4,["modelName"]="guidao02"}
,{["index"]=5,["modelName"]="guidao02"}
,{["index"]=6,["modelName"]="guidao02"}
,{["index"]=7,["modelName"]="guidao02"}
,{["index"]=8,["modelName"]="guidao03"}
,{["index"]=9,["modelName"]="guidao03"}
,{["index"]=10,["modelName"]="guidao03"}
}
,["key"]="1005",["modelScale"]=3,["angle"]=0,["id"]=1005,["namePos"]={0,0,0}
}
,[1007]={["infos"]={{["index"]=1,["modelName"]="zhuangjia01_2"}
,{["index"]=2,["modelName"]="zhuangjia01_2"}
,{["index"]=3,["modelName"]="zhuangjia01_2"}
,{["index"]=4,["modelName"]="zhuangjia01_2"}
,{["index"]=5,["modelName"]="zhuangjia01_2"}
,{["index"]=6,["modelName"]="zhuangjia01_2"}
,{["index"]=7,["modelName"]="zhuangjia01_2"}
,{["index"]=8,["modelName"]="zhuangjia01_2"}
,{["index"]=9,["modelName"]="zhuangjia01_2"}
,{["index"]=10,["modelName"]="zhuangjia01_2"}
}
,["key"]="1007",["modelScale"]=3,["angle"]=0,["id"]=1007,["namePos"]={0,0,0}
}
,[1009]={["infos"]={{["index"]=1,["modelName"]="zhuangbei01"}
,{["index"]=2,["modelName"]="zhuangbei01"}
,{["index"]=3,["modelName"]="zhuangbei01"}
,{["index"]=4,["modelName"]="zhuangbei02"}
,{["index"]=5,["modelName"]="zhuangbei02"}
,{["index"]=6,["modelName"]="zhuangbei02"}
,{["index"]=7,["modelName"]="zhuangbei02"}
,{["index"]=8,["modelName"]="zhuangbei03"}
,{["index"]=9,["modelName"]="zhuangbei03"}
,{["index"]=10,["modelName"]="zhuangbei03"}
}
,["key"]="1009",["modelScale"]=4,["angle"]=0,["id"]=1009,["namePos"]={0,0,0}
}
,[2002]={["infos"]={{["index"]=1,["modelName"]="zhanshu01"}
,{["index"]=2,["modelName"]="zhanshu01"}
,{["index"]=3,["modelName"]="zhanshu01"}
,{["index"]=4,["modelName"]="zhanshu02"}
,{["index"]=5,["modelName"]="zhanshu02"}
,{["index"]=6,["modelName"]="zhanshu02"}
,{["index"]=7,["modelName"]="zhanshu02"}
,{["index"]=8,["modelName"]="zhanshu03"}
,{["index"]=9,["modelName"]="zhanshu03"}
,{["index"]=10,["modelName"]="zhanshu03"}
}
,["key"]="2002",["modelScale"]=3,["angle"]=0,["id"]=2002,["namePos"]={0,0,0}
}
}

