_G["ConfigUnion"]={{["key"]="1",["sUnionName"]="RewardInfo",["id"]=1,["item"]={{["sCfgName"]="奖励表-常规",["index"]=1,["sCfgKey"]="RewardInfo1"}
,{["sCfgName"]="奖励表-抽卡",["index"]=2,["sCfgKey"]="RewardInfo2"}
,{["sCfgName"]="奖励表-关卡",["index"]=3,["sCfgKey"]="RewardInfo3"}
,{["sCfgName"]="奖励表-礼包",["index"]=4,["sCfgKey"]="RewardInfo4"}
,{["sCfgName"]="奖励表-兑换商店",["index"]=5,["sCfgKey"]="RewardInfo5"}
,{["sCfgName"]="奖励表-基地",["index"]=6,["sCfgKey"]="RewardInfo6"}
}
,["name"]="奖励表"}
,{["key"]="1",["sUnionName"]="MainLine",["id"]=2,["item"]={{["sCfgName"]="主线关卡",["index"]=1,["sCfgKey"]="MainLine1"}
,{["sCfgName"]="副本关卡",["index"]=2,["sCfgKey"]="MainLine2"}
,{["sCfgName"]="支线关卡",["index"]=3,["sCfgKey"]="MainLine3"}
,{["sCfgName"]="教程关卡",["index"]=4,["sCfgKey"]="MainLine4"}
,{["sCfgName"]="爬塔关卡",["index"]=5,["sCfgKey"]="MainLine5"}
,{["sCfgName"]="团战系统关卡",["index"]=6,["sCfgKey"]="MainLine6"}
,{["sCfgName"]="剧情活动关卡",["index"]=7,["sCfgKey"]="MainLine7"}
,{["sCfgName"]="讨伐活动关卡",["index"]=8,["sCfgKey"]="MainLine8"}
,{["sCfgName"]="纯剧情关卡",["index"]=9,["sCfgKey"]="MainLine9"}
,{["sCfgName"]="异构空间关卡",["index"]=10,["sCfgKey"]="MainLine10"}
,{["sCfgName"]="试炼关卡",["index"]=11,["sCfgKey"]="MainLine11"}
,{["sCfgName"]="十二星宫关卡",["index"]=12,["sCfgKey"]="MainLine12"}
,{["sCfgName"]="乱序演习关卡",["index"]=13,["sCfgKey"]="MainLine13"}
,{["sCfgName"]="战力派遣关卡",["index"]=14,["sCfgKey"]="MainLine14"}
,{["sCfgName"]="角斗场关卡",["index"]=15,["sCfgKey"]="MainLine15"}
,{["sCfgName"]="限制肉鸽爬塔关卡",["index"]=16,["sCfgKey"]="MainLine16"}
,{["sCfgName"]="多队战斗",["index"]=17,["sCfgKey"]="MainLine18"}
,{["sCfgName"]="深塔计划",["index"]=18,["sCfgKey"]="MainLine19"}
}
,["name"]="关卡表"}
,{["key"]="1",["sUnionName"]="ItemInfo",["id"]=3,["item"]={{["sCfgName"]="物品集合",["index"]=1,["sCfgKey"]="ItemInfo1"}
,{["sCfgName"]="宿舍家具",["index"]=2,["sCfgKey"]="ItemInfo2"}
,{["sCfgName"]="芯片（单个）表",["index"]=3,["sCfgKey"]="ItemInfo3"}
,{["sCfgName"]="头像框",["index"]=4,["sCfgKey"]="ItemInfo4"}
,{["sCfgName"]="头像",["index"]=5,["sCfgKey"]="ItemInfo5"}
,{["sCfgName"]="宠物相关",["index"]=6,["sCfgKey"]="ItemInfo6"}
,{["sCfgName"]="玩家称号",["index"]=7,["sCfgKey"]="ItemInfo7"}
,{["sCfgName"]="对战表情",["index"]=8,["sCfgKey"]="ItemInfo8"}
}
,["name"]="物品表"}
,{["key"]="1",["sUnionName"]="DungeonGroup",["id"]=4,["item"]={{["sCfgName"]="主线关卡分组",["index"]=1,["sCfgKey"]="DungeonGroup1"}
,{["sCfgName"]="剧情关卡分组",["index"]=2,["sCfgKey"]="DungeonGroup2"}
,{["sCfgName"]="角色关卡分组",["index"]=3,["sCfgKey"]="DungeonGroup3"}
,{["sCfgName"]="讨伐活动分组",["index"]=4,["sCfgKey"]="DungeonGroup4"}
,{["sCfgName"]="试炼活动分组",["index"]=5,["sCfgKey"]="DungeonGroup5"}
,{["sCfgName"]="十二星宫分组",["index"]=6,["sCfgKey"]="DungeonGroup6"}
,{["sCfgName"]="乱序演习分组",["index"]=7,["sCfgKey"]="DungeonGroup7"}
,{["sCfgName"]="战力派遣分组",["index"]=8,["sCfgKey"]="DungeonGroup8"}
,{["sCfgName"]="肉鸽爬塔分组",["index"]=9,["sCfgKey"]="DungeonGroup9"}
,{["sCfgName"]="多队战斗分组",["index"]=10,["sCfgKey"]="DungeonGroup11"}
,{["sCfgName"]="深塔计划分组",["index"]=11,["sCfgKey"]="DungeonGroup12"}
}
,["name"]="关卡分组表"}
,{["key"]="1",["sUnionName"]="TalkInfo",["id"]=5,["item"]={{["sCfgName"]="主线剧情",["index"]=1,["sCfgKey"]="TalkInfo1"}
,{["sCfgName"]="好感剧情",["index"]=2,["sCfgKey"]="TalkInfo2"}
,{["sCfgName"]="活动剧情",["index"]=3,["sCfgKey"]="TalkInfo3"}
,{["sCfgName"]="特殊剧情",["index"]=4,["sCfgKey"]="TalkInfo4"}
}
,["name"]="剧情表"}
,{["key"]="1",["sUnionName"]="Section",["id"]=6,["item"]={{["sCfgName"]="主线",["index"]=1,["sCfgKey"]="Section1"}
,{["sCfgName"]="材料",["index"]=2,["sCfgKey"]="Section2"}
,{["sCfgName"]="普通活动",["index"]=3,["sCfgKey"]="Section3"}
,{["sCfgName"]="教程",["index"]=4,["sCfgKey"]="Section4"}
,{["sCfgName"]="角色剧情活动",["index"]=5,["sCfgKey"]="Section5"}
,{["sCfgName"]="试炼",["index"]=6,["sCfgKey"]="Section6"}
}
,["name"]="章节表"}
,{["key"]="1",["sUnionName"]="CfgSensitiveWord",["id"]=7,["item"]={{["sCfgName"]="敏感字1",["index"]=1,["sCfgKey"]="CfgSensitiveWord1"}
,{["sCfgName"]="敏感字2",["index"]=2,["sCfgKey"]="CfgSensitiveWord2"}
,{["sCfgName"]="敏感字3",["index"]=3,["sCfgKey"]="CfgSensitiveWord3"}
}
,["name"]="敏感词表"}
,{["key"]="1",["sUnionName"]="Sound",["id"]=8,["item"]={{["sCfgName"]="角色普通语音",["index"]=1,["sCfgKey"]="Sound1"}
,{["sCfgName"]="角色皮肤语音",["index"]=2,["sCfgKey"]="Sound2"}
,{["sCfgName"]="插图语音",["index"]=3,["sCfgKey"]="Sound3"}
}
,["name"]="声音表"}
,{["key"]="1",["sUnionName"]="CfgArchiveMultiPicture",["id"]=9,["item"]={{["sCfgName"]="多人插图",["index"]=1,["sCfgKey"]="CfgArchiveMultiPicture1"}
,{["sCfgName"]="贴纸半身像",["index"]=2,["sCfgKey"]="CfgArchiveMultiPicture2"}
}
,["name"]="多人插图表"}
}

