_G["CfgPetWord"]={[103]={["id"]=103,["infos"]={{["word1"]="今天适合钓鱼~",["index"]=1,["animation"]="idle",["trigger"]=1,["time"]=4,["word2"]="该去钓鱼了~"}
,{["word1"]="钓具准备完毕~",["index"]=2,["animation"]="idle",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="钓鱼客准备动身~"}
,{["word1"]="呼噜~呼噜~",["index"]=3,["animation"]="sleep",["trigger"]=1,["time"]=4,["word2"]="Zzzz……"}
,{["word1"]="鱼……好多鱼……",["index"]=4,["animation"]="sleep",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="桶里全是鱼……"}
,{["word1"]="嗦面令我快乐~",["index"]=5,["animation"]="eat",["trigger"]=2,["time"]=4,["word2"]="美食令我充实~"}
,{["word1"]="好吃，爱吃~",["index"]=6,["animation"]="eat",["trigger"]=4,["time"]=4,["word2"]="想要再来一碗……"}
,{["word1"]="哼哼哼~♪~哼~♪",["index"]=7,["animation"]="wash",["trigger"]=2,["time"]=4,["word2"]="我爱洗澡皮肤好好~"}
,{["word1"]="还想再泡五分钟~",["index"]=8,["animation"]="wash",["trigger"]=4,["time"]=4,["word2"]="不留一点污垢~"}
,{["word1"]="暖乎乎~好舒服~",["index"]=9,["animation"]="clean",["trigger"]=2,["time"]=4,["word2"]="舒适享受中~"}
,{["word1"]="护理完毕~精力充足~",["index"]=10,["animation"]="clean",["trigger"]=4,["time"]=4,["word2"]="感觉更加精神了~"}
,{["word1"]="有鱼上钩了~",["index"]=11,["animation"]="play",["trigger"]=2,["time"]=4,["word2"]="钓鱼客不能没有鱼~"}
,{["word1"]="别把我和鱼分开……",["index"]=12,["animation"]="play",["trigger"]=4,["time"]=4,["word2"]="我要和鱼永远在一起~"}
,{["word1"]="休闲时刻到~！",["index"]=13,["animation"]="walk",["trigger"]=1,["time"]=4,["word2"]="钓鱼~钓鱼~~"}
,{["word1"]="钓鱼客永不空军！",["index"]=14,["animation"]="walk",["trigger"]=2,["time"]=4,["word2"]="钓鱼其乐无穷！"}
,{["word1"]="怎么没有鱼上钩……",["index"]=15,["animation"]="walk",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="平心~静气~"}
,{["word1"]="该回家了~",["index"]=16,["animation"]="walk",["trigger"]=4,["time"]=4,["word2"]="快乐的时间完结了~"}
,{["word1"]="运动让我健康~",["index"]=17,["animation"]="sport",["trigger"]=1,["time"]=4,["word2"]="生命在于运动！"}
,{["word1"]="努力！奔跑！拼搏！",["index"]=18,["animation"]="sport",["trigger"]=2,["time"]=4,["word2"]="已经跑不动了……"}
,{["word1"]="三分钟了……跑不动了……",["index"]=19,["animation"]="sport",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="什么时候才能结束……"}
,{["word1"]="终于能停下来了……",["index"]=20,["animation"]="sport",["trigger"]=4,["time"]=4,["word2"]="要累趴了……"}
,{["word1"]="哼哼哼~♪~哼~♪",["index"]=21,["animation"]="move",["trigger"]=2,["time"]=4,["word2"]="哼哼哼~♪~哼~♪"}
}
,["key"]="103"}
,[101]={["id"]=101,["infos"]={{["word1"]="今天天气不错~",["index"]=1,["animation"]="idle",["trigger"]=1,["time"]=4,["word2"]="你好~"}
,{["word1"]="有点无聊了~",["index"]=2,["animation"]="idle",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="要干什么呢~"}
,{["word1"]="呼~呼~",["index"]=3,["animation"]="sleep",["trigger"]=1,["time"]=4,["word2"]="睡觉~好舒服~"}
,{["word1"]="饼干……好多饼干……",["index"]=4,["animation"]="sleep",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="Zzzz……"}
,{["word1"]="嗷呜~好吃~",["index"]=5,["animation"]="eat",["trigger"]=2,["time"]=4,["word2"]="香香~美味~"}
,{["word1"]="好吃，爱吃~",["index"]=6,["animation"]="eat",["trigger"]=4,["time"]=4,["word2"]="能不能再来一份？"}
,{["word1"]="真舒服呀~",["index"]=7,["animation"]="wash",["trigger"]=2,["time"]=4,["word2"]="我爱洗澡身体好好~"}
,{["word1"]="干干净净，身心舒畅~",["index"]=8,["animation"]="wash",["trigger"]=4,["time"]=4,["word2"]="舒服得要睡着了……"}
,{["word1"]="普酱需要天天护理~",["index"]=9,["animation"]="clean",["trigger"]=2,["time"]=4,["word2"]="美貌需要好好呵护~"}
,{["word1"]="护理完毕~",["index"]=10,["animation"]="clean",["trigger"]=4,["time"]=4,["word2"]="美貌指数又上升了~"}
,{["word1"]="举高高~骑茄茄~",["index"]=11,["animation"]="play",["trigger"]=2,["time"]=4,["word2"]="飞吧~遨游碎星~"}
,{["word1"]="可以再来一次吗？",["index"]=12,["animation"]="play",["trigger"]=4,["time"]=4,["word2"]="我还想玩~"}
,{["word1"]="被发现在偷懒了呢~",["index"]=13,["animation"]="walk",["trigger"]=1,["time"]=4,["word2"]="放松使我快乐~"}
,{["word1"]="轻松一刻~",["index"]=14,["animation"]="walk",["trigger"]=2,["time"]=4,["word2"]="该做点什么好呢~"}
,{["word1"]="想回家~想回家~",["index"]=15,["animation"]="walk",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="为什么散步这么累？"}
,{["word1"]="回家的感觉真好~",["index"]=16,["animation"]="walk",["trigger"]=4,["time"]=4,["word2"]="我要累晕了……"}
,{["word1"]="运动让我健康~",["index"]=17,["animation"]="sport",["trigger"]=1,["time"]=4,["word2"]="运动让我快乐~"}
,{["word1"]="我累了，该休息了……",["index"]=18,["animation"]="sport",["trigger"]=2,["time"]=4,["word2"]="运动过度是有害的……"}
,{["word1"]="好累啊~",["index"]=19,["animation"]="sport",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="还有多久结束~"}
,{["word1"]="普酱要累晕了……",["index"]=20,["animation"]="sport",["trigger"]=4,["time"]=4,["word2"]="终于结束了……"}
,{["word1"]="被发现在偷懒了呢~",["index"]=21,["animation"]="move",["trigger"]=2,["time"]=4,["word2"]="放松使我快乐~"}
}
,["key"]="101"}
,[102]={["id"]=102,["infos"]={{["word1"]="今天天气不错~",["index"]=1,["animation"]="idle",["trigger"]=1,["time"]=4,["word2"]="早上、中午、晚上好~"}
,{["word1"]="有点无聊了~",["index"]=2,["animation"]="idle",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="要干什么呢~"}
,{["word1"]="呼~呼~",["index"]=3,["animation"]="sleep",["trigger"]=1,["time"]=4,["word2"]="被子~要掉了~"}
,{["word1"]="天还没亮，我还要睡~",["index"]=4,["animation"]="sleep",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="呼呼呼~"}
,{["word1"]="好吃~好吃~",["index"]=5,["animation"]="eat",["trigger"]=2,["time"]=4,["word2"]="暴风吸入~"}
,{["word1"]="好吃，爱吃~",["index"]=6,["animation"]="eat",["trigger"]=4,["time"]=4,["word2"]="再来一份！"}
,{["word1"]="哼哼~♪~哼~♪~",["index"]=7,["animation"]="wash",["trigger"]=2,["time"]=4,["word2"]="洗去所有污垢~"}
,{["word1"]="干净又清爽~",["index"]=8,["animation"]="wash",["trigger"]=4,["time"]=4,["word2"]="我是不是更光滑了？"}
,{["word1"]="每日护理开始~",["index"]=9,["animation"]="clean",["trigger"]=2,["time"]=4,["word2"]="避免脱水，更加新鲜~"}
,{["word1"]="水分补充完毕~",["index"]=10,["animation"]="clean",["trigger"]=4,["time"]=4,["word2"]="清新舒爽每一天~"}
,{["word1"]="音乐时间到！",["index"]=11,["animation"]="play",["trigger"]=2,["time"]=4,["word2"]="随音乐起舞吧~"}
,{["word1"]="我还没玩够呢~",["index"]=12,["animation"]="play",["trigger"]=4,["time"]=4,["word2"]="再让我玩五分钟吧~"}
,{["word1"]="芭蕾转转转~",["index"]=13,["animation"]="walk",["trigger"]=1,["time"]=4,["word2"]="转圈使我放松~"}
,{["word1"]="我要钻入恒心~",["index"]=14,["animation"]="walk",["trigger"]=2,["time"]=4,["word2"]="轻松~自由~快乐~"}
,{["word1"]="感觉脚底在燃烧……",["index"]=15,["animation"]="walk",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="为什么感觉这么晕——"}
,{["word1"]="终于能停下来了……",["index"]=16,["animation"]="walk",["trigger"]=4,["time"]=4,["word2"]="我的腿有自己的想法……"}
,{["word1"]="小强飞高高~",["index"]=17,["animation"]="sport",["trigger"]=1,["time"]=4,["word2"]="快乐的运动时刻~"}
,{["word1"]="我讨厌运动~",["index"]=18,["animation"]="sport",["trigger"]=2,["time"]=4,["word2"]="为什么我要运动~"}
,{["word1"]="太累了~",["index"]=19,["animation"]="sport",["holdTime"]=180,["time"]=4,["trigger"]=3,["word2"]="为什么放松会更累？"}
,{["word1"]="小强，你没事吧……",["index"]=20,["animation"]="sport",["trigger"]=4,["time"]=4,["word2"]="终于完成了……"}
,{["word1"]="感觉脚底在燃烧……",["index"]=21,["animation"]="move",["trigger"]=2,["time"]=4,["word2"]="为什么感觉这么晕——"}
}
,["key"]="102"}
}

