_G["CfgVoucher"]={{["id"]=1,["reduceId"]=10002,["minCost"]=100,["mixDiscount"]=true,["name"]="通用优惠券Ⅰ",["mixUse"]=false,["describe"]=[[可用于补给站内所有商品的优惠券。
普普通通的优惠券，亦是探索队每日辛勤的回报。]],["reduceNum"]=50,["key"]="1",["voucherType"]=1}
,{["id"]=2,["reduceId"]=10002,["minCost"]=200,["mixDiscount"]=true,["name"]="通用优惠券Ⅱ",["mixUse"]=false,["describe"]=[[可用于补给站内所有商品的优惠券。
限量发放的优惠券，优惠力度足以匹配一场胜利。]],["reduceNum"]=100,["key"]="2",["voucherType"]=1}
,{["id"]=3,["reduceId"]=10002,["minCost"]=300,["mixDiscount"]=true,["name"]="通用优惠券Ⅲ",["mixUse"]=false,["describe"]=[[可用于补给站内所有商品的优惠券。
烫金定制的优惠券，厚重的手感下承载着无以言说的荣耀。]],["reduceNum"]=150,["key"]="3",["voucherType"]=1}
,{["id"]=4,["reduceId"]=10002,["minCost"]=100,["mixDiscount"]=true,["name"]="时装优惠券Ⅰ",["mixUse"]=false,["describe"]=[[时装专属优惠券。
为鼓励队员士气，由后勤部门定量发放的优惠名额，可在时装商店享受少量优惠。]],["reduceNum"]=50,["key"]="4",["voucherType"]=2}
,{["id"]=5,["reduceId"]=10002,["minCost"]=200,["mixDiscount"]=true,["name"]="时装优惠券Ⅱ",["mixUse"]=false,["describe"]=[[时装专属优惠券。
为嘉奖队员功绩，由后勤部门额外批准的私人订制，可在时装商店享受中量优惠。]],["reduceNum"]=100,["key"]="5",["voucherType"]=2}
,{["voucherType"]=2,["reduceId"]=10002,["minCost"]=300,["mixDiscount"]=true,["mixUse"]=false,["key"]="6",["minLevel"]=10,["describe"]=[[时装专属优惠券。
为铭记队员荣誉，由后勤部门精心安排的内部渠道，可在时装商店享受大量优惠。]],["reduceNum"]=150,["name"]="时装优惠券Ⅲ",["id"]=6}
,{["id"]=7,["reduceId"]=10002,["minCost"]=100,["mixDiscount"]=true,["name"]="插画优惠券Ⅰ",["mixUse"]=false,["describe"]=[[插画专属优惠券。
从名为和平的幻梦中，记录下最珍贵的一瞬——好不容易得来的假期，可要好好把握呀！]],["reduceNum"]=50,["key"]="7",["voucherType"]=3}
,{["id"]=8,["reduceId"]=10002,["minCost"]=200,["mixDiscount"]=true,["name"]="插画优惠券Ⅱ",["mixUse"]=false,["describe"]=[[插画专属优惠券。
从名为和平的幻梦中，记录下最珍贵的一瞬——假期余额充足，稍微放肆些也不要紧吧？]],["reduceNum"]=100,["key"]="8",["voucherType"]=3}
,{["id"]=9,["reduceId"]=10002,["minCost"]=300,["mixDiscount"]=true,["name"]="插画优惠券Ⅲ",["mixUse"]=false,["describe"]=[[插画专属优惠券。
从名为和平的幻梦中，记录下最珍贵的一瞬——愿时光终结在这美好一刻。]],["reduceNum"]=150,["key"]="9",["voucherType"]=3}
}

