_G["CfgOpenCondition"]={["ColosseumView"]={["key"]="ColosseumView",["id"]="ColosseumView",["conditions"]={2120}
,["sName"]="角斗场"}
,["GuildMenu"]={["key"]="GuildMenu",["id"]="GuildMenu",["conditions"]={2110}
,["sName"]="公会"}
,["MailView"]={["conditions"]={2003}
,["key"]="MailView",["jump"]=90001,["open_tips"]=1,["sName"]="邮件",["icon"]="MailView",["id"]="MailView"}
,["BadgeView"]={["conditions"]={2001}
,["key"]="BadgeView",["open_tips"]=1,["sName"]="徽章",["icon"]="Badge",["id"]="BadgeView"}
,["ExplorationMain"]={["conditions"]={2007}
,["key"]="ExplorationMain",["open_tips"]=1,["sName"]="勘探指南",["icon"]="ExplorationMain",["id"]="ExplorationMain"}
,["RogueTView"]={["key"]="RogueTView",["id"]="RogueTView",["conditions"]={2120}
,["sName"]="能力测验"}
,["Section"]={["id"]="Section",["sName"]="出击",["key"]="Section"}
,["RichManMain"]={["key"]="RichManMain",["id"]="RichManMain",["conditions"]={2008}
,["sName"]="光影奇境"}
,["RogueView"]={["key"]="RogueView",["id"]="RogueView",["conditions"]={2120}
,["sName"]="乱序演习"}
,["ArchiveView"]={["conditions"]={2103}
,["key"]="ArchiveView",["open_tips"]=1,["sName"]="档案",["icon"]="ArchiveView",["id"]="ArchiveView"}
,["SettingView"]={["id"]="SettingView",["sName"]="设置",["key"]="SettingView"}
,["Dorm"]={["conditions"]={2005}
,["key"]="Dorm",["open_tips"]=1,["sName"]="宿舍",["icon"]="Dorm",["id"]="Dorm"}
,["Achievement"]={["conditions"]={2105}
,["key"]="Achievement",["open_tips"]=1,["sName"]="成就",["icon"]="Achievement",["id"]="Achievement"}
,["SkinRebate"]={["key"]="SkinRebate",["id"]="SkinRebate",["conditions"]={2002}
,["sName"]="衣惠有礼"}
,["MultTeamBattleMain"]={["key"]="MultTeamBattleMain",["id"]="MultTeamBattleMain",["conditions"]={2125}
,["sName"]="递归沙盒"}
,["PuzzleActivity"]={["key"]="PuzzleActivity",["id"]="PuzzleActivity",["conditions"]={2120}
,["sName"]="拾光剪影"}
,["ExerciseLView"]={["conditions"]={2114}
,["key"]="ExerciseLView",["open_tips"]=1,["sName"]="镜像竞技",["icon"]="Arena",["id"]="ExerciseLView"}
,["CourseView"]={["conditions"]={2001}
,["key"]="CourseView",["open_tips"]=1,["sName"]="教程",["icon"]="CourseView",["id"]="CourseView"}
,["FriendView"]={["conditions"]={2001}
,["key"]="FriendView",["open_tips"]=1,["sName"]="好友",["icon"]="FriendView",["id"]="FriendView"}
,["ActivityListView"]={["conditions"]={2007}
,["key"]="ActivityListView",["open_tips"]=1,["sName"]="活动界面",["icon"]="ActivityListView",["id"]="ActivityListView"}
,["CoolView"]={["id"]="CoolView",["sName"]="冷却",["key"]="CoolView"}
,["ShopView"]={["conditions"]={2002}
,["key"]="ShopView",["open_tips"]=1,["sName"]="商店",["icon"]="ShopView",["id"]="ShopView"}
,["PlayerAbility"]={["conditions"]={2007}
,["key"]="PlayerAbility",["open_tips"]=1,["sName"]="战术",["icon"]="PlayerAbility",["id"]="PlayerAbility"}
,["TowerListView"]={["key"]="TowerListView",["id"]="TowerListView",["conditions"]={2120}
,["sName"]="异构空间"}
,["TowerDeep"]={["key"]="TowerDeep",["id"]="TowerDeep",["conditions"]={2125}
,["sName"]="深塔计划"}
,["TowerView"]={["key"]="TowerView",["id"]="TowerView",["conditions"]={2120}
,["sName"]="异构空间"}
,["PlayerView"]={["key"]="PlayerView",["id"]="PlayerView",["conditions"]={2001}
,["sName"]="玩家"}
,["LovePlusView"]={["key"]="LovePlusView",["id"]="LovePlusView",["conditions"]={2007}
,["sName"]="时光恋曲"}
,["Matrix"]={["conditions"]={2005}
,["sSceneName"]="Matrix",["key"]="Matrix",["open_tips"]=1,["sName"]="基地",["icon"]="Matrix",["id"]="Matrix"}
,["RiddleMain"]={["key"]="RiddleMain",["id"]="RiddleMain",["conditions"]={2007}
,["sName"]="天灯映月"}
,["SignInDuanWu"]={["key"]="SignInDuanWu",["id"]="SignInDuanWu",["conditions"]={2007}
,["sName"]="龙舟争霸赛"}
,["Bag"]={["key"]="Bag",["id"]="Bag",["conditions"]={2002}
,["sName"]="仓库"}
,["RogueSView"]={["key"]="RogueSView",["id"]="RogueSView",["conditions"]={2120}
,["sName"]="战力调遣"}
,["LuckyGachaMain"]={["key"]="LuckyGachaMain",["id"]="LuckyGachaMain",["conditions"]={2007}
,["sName"]="扭蛋机"}
,["TeamView"]={["id"]="TeamView",["sName"]="编队",["key"]="TeamView"}
,["SignInView"]={["id"]="SignInView",["sName"]="签到",["key"]="SignInView"}
,["SpecialActivityView"]={["key"]="SpecialActivityView",["id"]="SpecialActivityView",["conditions"]={2007}
,["sName"]="特别馈赠"}
,["RoleListNormal"]={["id"]="RoleListNormal",["sName"]="角色",["key"]="RoleListNormal"}
,["MissionView"]={["conditions"]={2002}
,["key"]="MissionView",["open_tips"]=1,["sName"]="任务",["icon"]="MissionView",["id"]="MissionView"}
,["CollaborationMain"]={["key"]="CollaborationMain",["id"]="CollaborationMain",["conditions"]={2007}
,["sName"]="协同作战"}
,["PetMain"]={["key"]="PetMain",["id"]="PetMain",["conditions"]={2007}
,["sName"]="萌宠进化论"}
,["CreateView"]={["id"]="CreateView",["sName"]="抽卡",["key"]="CreateView"}
,["ExtraActivityView"]={["key"]="ExtraActivityView",["id"]="ExtraActivityView",["conditions"]={2002}
,["sName"]="付费活动"}
}

