_G["CfgArchiveIllustration"]={{["small"]="arch_seashore",["infos"]={{["shopId"]=80401,["board_id"]=2,["index"]=1,["icon"]="arch_seashore"}
,{["shopId"]=80402,["board_id"]=4,["index"]=2,["icon"]="arch_summer_rendezvous"}
,{["board_id"]=23,["index"]=3,["icon"]="arch_summer_swimming_party"}
,{["shopId"]=80415,["board_id"]=24,["index"]=4,["icon"]="arch_beach_holidays"}
,{["shopId"]=80416,["board_id"]=25,["index"]=5,["icon"]="arch_cool_bright_summer"}
,{["shopId"]=80417,["board_id"]=26,["index"]=6,["icon"]="arch_warm_summer"}
,{["board_id"]=28,["index"]=7,["icon"]="arch_coolness_of_summer"}
,{["board_id"]=43,["index"]=8,["icon"]="arch_swimmer_assemble"}
,{["board_id"]=49,["index"]=9,["icon"]="arch_beach_playtime"}
,{["board_id"]=71,["index"]=10,["icon"]="arch_master_of_tides"}
,{["shopId"]=80441,["board_id"]=77,["index"]=11,["icon"]="arch_radiant_summer_sojourn"}
,{["shopId"]=80442,["board_id"]=78,["index"]=12,["icon"]="arch_sands_of_summer_heat"}
,{["shopId"]=80443,["board_id"]=79,["index"]=13,["icon"]="arch_beach_picnic"}
}
,["key"]="1",["id"]=1,["name"]="海边度假"}
,{["small"]="arch_three_people",["infos"]={{["board_id"]=1,["index"]=1,["icon"]="arch_three_people"}
,{["board_id"]=3,["index"]=2,["icon"]="arch_kadya_liedown"}
,{["shopId"]=80405,["board_id"]=7,["index"]=3,["icon"]="arch_trytomoveforward"}
,{["board_id"]=9,["index"]=4,["icon"]="arch_play_time"}
,{["board_id"]=10,["index"]=5,["icon"]="arch_relaxing_afternoon"}
,{["shopId"]=80407,["board_id"]=13,["index"]=6,["icon"]="arch_greenhouse"}
,{["shopId"]=80408,["board_id"]=14,["index"]=7,["icon"]="arch_starry_night"}
,{["board_id"]=15,["index"]=8,["icon"]="arch_fun_with_mew"}
,{["shopId"]=80409,["board_id"]=16,["index"]=9,["icon"]="arch_tender_dream"}
,{["shopId"]=80410,["board_id"]=17,["index"]=10,["icon"]="arch_intoxicated_shadow"}
,{["shopId"]=80411,["board_id"]=18,["index"]=11,["icon"]="arch_weightless_space"}
,{["shopId"]=80427,["board_id"]=56,["index"]=12,["icon"]="arch_dress_up_game"}
,{["shopId"]=80429,["board_id"]=59,["index"]=13,["icon"]="arch_pink_love"}
,{["shopId"]=80430,["board_id"]=60,["index"]=14,["icon"]="arch_cozy_cooking"}
,{["shopId"]=80431,["board_id"]=61,["index"]=15,["icon"]="arch_feeding_with_affection"}
,{["shopId"]=80433,["board_id"]=65,["index"]=16,["icon"]="arch_idol_dressing_room"}
,{["shopId"]=80434,["board_id"]=66,["index"]=17,["icon"]="arch_foot_fashion"}
,{["shopId"]=80444,["board_id"]=83,["index"]=18,["icon"]="arch_ephemeral_indulgence"}
,{["shopId"]=80459,["board_id"]=84,["index"]=19,["icon"]="arch_Tea_Time"}
,{["shopId"]=80460,["board_id"]=85,["index"]=20,["icon"]="arch_Dreamlike_Picture"}
,{["shopId"]=80465,["board_id"]=98,["index"]=21,["icon"]="arch_Changing_Room_Shenanigans"}
,{["board_id"]=100,["index"]=22,["icon"]="arch_Locker_Room_Party"}
,{["board_id"]=101,["index"]=23,["icon"]="arch_Nocturnal_Mystery_Gift"}
}
,["key"]="2",["id"]=2,["name"]="宿舍故事"}
,{["small"]="arch_shimmering_feast",["infos"]={{["shopId"]=80403,["board_id"]=5,["index"]=1,["icon"]="arch_shimmering_feast"}
,{["shopId"]=80404,["board_id"]=6,["index"]=2,["icon"]="arch_fireworks_IoIent"}
,{["shopId"]=80413,["board_id"]=19,["index"]=3,["icon"]="arch_moonlight_sharing"}
,{["board_id"]=30,["index"]=4,["icon"]="arch_starry_lotus_fire"}
,{["shopId"]=80437,["board_id"]=57,["index"]=5,["icon"]="arch_chinese_music_party"}
,{["shopId"]=80461,["board_id"]=58,["index"]=6,["icon"]="arch_hang_out_in_lotus"}
}
,["key"]="3",["id"]=3,["name"]="佳节逐禧"}
,{["small"]="arch_base_check",["infos"]={{["board_id"]=8,["index"]=1,["icon"]="arch_base_check"}
}
,["key"]="4",["id"]=4,["name"]="作战准备"}
,{["small"]="arch_bestie_agent",["infos"]={{["shopId"]=80406,["board_id"]=11,["index"]=1,["icon"]="arch_bestie_agent"}
}
,["key"]="5",["id"]=5,["name"]="娇痴颐使"}
,{["small"]="arch_trip_in_the_milky_way",["infos"]={{["board_id"]=12,["index"]=1,["icon"]="arch_trip_in_the_milky_way"}
,{["shopId"]=80412,["board_id"]=20,["index"]=2,["icon"]="arch_guard_of_iron_bastion"}
,{["board_id"]=21,["index"]=3,["icon"]="arch_silhouette_in_a_moment"}
,{["board_id"]=22,["index"]=4,["icon"]="arch_snowland_gods"}
,{["board_id"]=31,["index"]=5,["icon"]="arch_sign_of_mutation"}
,{["board_id"]=32,["index"]=6,["icon"]="arch_waves_tumble"}
,{["board_id"]=33,["index"]=7,["icon"]="arch_rainbow_in_the_sky"}
,{["board_id"]=35,["index"]=8,["icon"]="arch_person_on_the_darknet"}
,{["board_id"]=36,["index"]=9,["icon"]="arch_rebuilding_together"}
,{["board_id"]=40,["index"]=10,["icon"]="arch_a_narrow_escape"}
,{["board_id"]=41,["index"]=11,["icon"]="arch_black_cocoon_rebecca"}
,{["board_id"]=42,["index"]=12,["icon"]="arch_wave_and_vortex"}
,{["shopId"]=80423,["board_id"]=47,["index"]=13,["icon"]="arch_golden_celebration"}
,{["board_id"]=52,["index"]=14,["icon"]="arch_voice_of_the_wild"}
,{["board_id"]=53,["index"]=15,["icon"]="arch_a_sweet_moment"}
,{["board_id"]=63,["index"]=16,["icon"]="arch_mirage_of_splendor"}
,{["board_id"]=70,["index"]=17,["icon"]="arch_calm_soak"}
,{["board_id"]=73,["index"]=18,["icon"]="arch_quiet_nook"}
,{["board_id"]=74,["index"]=19,["icon"]="arch_leisurely_picnic"}
}
,["key"]="6",["id"]=6,["name"]="寰宇梦境"}
,{["small"]="arch_dance_for_joy",["infos"]={{["board_id"]=27,["index"]=1,["icon"]="arch_dance_for_joy"}
,{["board_id"]=51,["index"]=2,["icon"]="arch_anniversary_party"}
,{["board_id"]=55,["index"]=3,["icon"]="arch_whole_family_have_fun"}
,{["board_id"]=69,["index"]=4,["icon"]="arch_labor_leisure"}
}
,["key"]="7",["id"]=7,["name"]="涂色速写"}
,{["small"]="arch_camping_with_fireworks",["infos"]={{["shopId"]=80418,["board_id"]=29,["index"]=1,["icon"]="arch_camping_with_fireworks"}
,{["shopId"]=80421,["board_id"]=45,["index"]=2,["icon"]="arch_trail_of_cases"}
,{["shopId"]=80432,["board_id"]=62,["index"]=3,["icon"]="arch_dusk_of_summer"}
,{["shopId"]=80435,["board_id"]=67,["index"]=4,["icon"]="arch_hot_spring_night_talk"}
,{["shopId"]=80436,["board_id"]=68,["index"]=5,["icon"]="arch_thin_gorgeous_snow"}
,{["board_id"]=97,["index"]=6,["icon"]="arch_jump_for_joy"}
,{["shopId"]=80466,["board_id"]=99,["index"]=7,["icon"]="arch_Brilliant_Mirror_Image"}
,{["board_id"]=104,["index"]=8,["icon"]="mult_A_Night_in_Scarlet"}
}
,["key"]="8",["id"]=8,["name"]="闲适假日"}
,{["small"]="arch_law_of_the_streets",["infos"]={{["shopId"]=80419,["board_id"]=39,["index"]=1,["icon"]="arch_law_of_the_streets"}
,{["shopId"]=80420,["board_id"]=44,["index"]=2,["icon"]="arch_fantastic_curtain_raiser"}
,{["shopId"]=80422,["board_id"]=46,["index"]=3,["icon"]="arch_double_feature"}
,{["shopId"]=80424,["board_id"]=48,["index"]=4,["icon"]="arch_alley_corner_crisis"}
,{["shopId"]=80426,["board_id"]=50,["index"]=5,["icon"]="arch_twilight_invitation"}
,{["shopId"]=80428,["board_id"]=38,["index"]=6,["icon"]="arch_rainy_night_jeopardy"}
,{["shopId"]=80438,["board_id"]=72,["index"]=7,["icon"]="arch_starting_raid"}
,{["shopId"]=80467,["board_id"]=102,["index"]=8,["icon"]="arch_Alluring_Set"}
}
,["key"]="9",["id"]=9,["name"]="都市掠影"}
,{["small"]="arch_decisiv_moment",["infos"]={{["board_id"]=64,["index"]=1,["icon"]="arch_decisiv_moment"}
,{["shopId"]=80439,["board_id"]=75,["index"]=2,["icon"]="arch_contention_arena"}
,{["shopId"]=80440,["board_id"]=76,["index"]=3,["icon"]="arch_knockout"}
}
,["key"]="10",["id"]=10,["name"]="活力瞬间"}
,{["small"]="arch_changing_moment",["infos"]={{["board_id"]=86,["index"]=1,["icon"]="arch_changing_moment"}
,{["board_id"]=87,["index"]=2,["icon"]="arch_woodland_search"}
,{["board_id"]=88,["index"]=3,["icon"]="arch_soul_confession"}
,{["board_id"]=89,["index"]=4,["icon"]="arch_dusk_shore"}
,{["board_id"]=90,["index"]=5,["icon"]="arch_Brilliant_Night"}
}
,["key"]="11",["id"]=11,["name"]="恋色风景"}
,{["small"]="arch_The_Care_in_Check-ups",["infos"]={{["shopId"]=80462,["board_id"]=91,["index"]=1,["icon"]="arch_The_Care_in_Check-ups"}
,{["shopId"]=80463,["board_id"]=92,["index"]=2,["icon"]="arch_Soul-Searching_Consultation"}
}
,["key"]="12",["id"]=12,["name"]="暖心呵护"}
}

