_G["CfgRolePosEnum"]={{["key"]="1",["id"]=1,["sName"]="护盾",["icon"]="1",["sortIcon"]={{1,"RolePos/1",1.2,0.3}
}
}
,{["key"]="2",["id"]=2,["sName"]="输出",["icon"]="2",["sortIcon"]={{1,"RolePos/2",1.2,0.3}
}
}
,{["key"]="3",["id"]=3,["sName"]="反击",["icon"]="3",["sortIcon"]={{1,"RolePos/3",1.2,0.3}
}
}
,{["key"]="4",["id"]=4,["sName"]="反伤",["icon"]="4",["sortIcon"]={{1,"RolePos/4",1.2,0.3}
}
}
,{["key"]="5",["id"]=5,["sName"]="治疗",["icon"]="5",["sortIcon"]={{1,"RolePos/5",1.2,0.3}
}
}
,{["key"]="6",["id"]=6,["sName"]="防御",["icon"]="6",["sortIcon"]={{1,"RolePos/6",1.2,0.3}
}
}
,{["key"]="7",["id"]=7,["sName"]="辅助",["icon"]="7",["sortIcon"]={{1,"RolePos/7",1.2,0.3}
}
}
,{["key"]="8",["id"]=8,["sName"]="控制",["icon"]="8",["sortIcon"]={{1,"RolePos/8",1.2,0.3}
}
}
,{["key"]="9",["id"]=9,["sName"]="协击",["icon"]="9",["sortIcon"]={{1,"RolePos/9",1.2,0.3}
}
}
}

