_G["CfgLifeBuffer"]={{["jVal"]={0.2}
,["id"]=1,["bIsShow"]=false,["oldName"]="角色EXP",["sDesc"]="同伴经验加成20%（装备用）",["nType"]=22,["name"]="角色EXP",["bIsAdd"]=false,["key"]="1",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.3}
,["id"]=2,["bIsShow"]=false,["oldName"]="角色EXP",["sDesc"]="同伴经验加成30%（装备用）",["nType"]=22,["name"]="角色EXP",["bIsAdd"]=false,["key"]="2",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.4}
,["id"]=3,["bIsShow"]=false,["oldName"]="角色EXP",["sDesc"]="同伴经验加成40%（装备用）",["nType"]=22,["name"]="角色EXP",["bIsAdd"]=false,["key"]="3",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.5}
,["id"]=4,["bIsShow"]=true,["oldName"]="角色EXP",["sDesc"]="副本战斗经验加成+50%（道具1天）",["nType"]=22,["name"]="角色EXP",["nSeconds"]=86400,["bIsAdd"]=false,["key"]="4",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={1}
,["id"]=5,["bIsShow"]=true,["oldName"]="角色EXP",["sDesc"]="同伴经验加成100%（节日用）",["nType"]=22,["name"]="角色EXP",["bIsAdd"]=false,["key"]="5",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.1}
,["id"]=6,["bIsShow"]=false,["oldName"]="玩家EXP",["sDesc"]="玩家经验加成10%（装备用）",["nType"]=23,["name"]="玩家EXP",["bIsAdd"]=false,["key"]="6",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.2}
,["id"]=7,["bIsShow"]=false,["oldName"]="玩家EXP",["sDesc"]="玩家经验加成20%（装备用）",["nType"]=23,["name"]="玩家EXP",["bIsAdd"]=false,["key"]="7",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.3}
,["id"]=8,["bIsShow"]=false,["oldName"]="玩家EXP",["sDesc"]="玩家经验加成30%（装备用）",["nType"]=23,["name"]="玩家EXP",["bIsAdd"]=false,["key"]="8",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.5}
,["id"]=9,["bIsShow"]=true,["oldName"]="玩家EXP",["sDesc"]="指挥官经验加成+50%（道具1天）",["nType"]=23,["name"]="玩家EXP",["nSeconds"]=86400,["bIsAdd"]=false,["key"]="9",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={1}
,["id"]=10,["bIsShow"]=true,["oldName"]="玩家EXP",["sDesc"]="玩家经验加成100%（节日用）",["nType"]=23,["name"]="玩家EXP",["bIsAdd"]=false,["key"]="10",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.1}
,["id"]=11,["bIsShow"]=false,["oldName"]="获得金币",["sDesc"]="金币加成10%（装备用）",["nType"]=24,["name"]="获得金币",["bIsAdd"]=false,["key"]="11",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.2}
,["id"]=12,["bIsShow"]=false,["oldName"]="获得金币",["sDesc"]="金币加成20%（装备用）",["nType"]=24,["name"]="获得金币",["bIsAdd"]=false,["key"]="12",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.3}
,["id"]=13,["bIsShow"]=false,["oldName"]="获得金币",["sDesc"]="金币加成30%（装备用）",["nType"]=24,["name"]="获得金币",["bIsAdd"]=false,["key"]="13",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.5}
,["id"]=14,["bIsShow"]=true,["oldName"]="获得金币",["sDesc"]="金币加成50%（道具1天）",["nType"]=24,["name"]="获得金币",["nSeconds"]=86400,["bIsAdd"]=false,["key"]="14",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={1}
,["id"]=15,["bIsShow"]=true,["oldName"]="获得金币",["sDesc"]="金币加成100%（节日用）",["nType"]=24,["name"]="获得金币",["bIsAdd"]=false,["key"]="15",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.1}
,["id"]=16,["bIsShow"]=true,["oldName"]="角色EXP",["sDesc"]="副本战斗角色经验+10%",["nType"]=22,["name"]="角色EXP",["bIsAdd"]=true,["key"]="16",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.1}
,["id"]=17,["bIsShow"]=true,["oldName"]="玩家EXP",["sDesc"]="副本战斗指挥官经验+10%",["nType"]=23,["name"]="玩家EXP",["bIsAdd"]=true,["key"]="17",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.1}
,["id"]=18,["bIsShow"]=true,["oldName"]="获得金币",["sDesc"]="副本战斗金币+10%",["nType"]=24,["name"]="获得金币",["bIsAdd"]=true,["key"]="18",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.25}
,["id"]=19,["bIsShow"]=false,["oldName"]="上阵COST",["sDesc"]="上阵COST+25",["nType"]=21,["name"]="上阵COST",["bIsAdd"]=true,["key"]="19",["icon"]="2011",["isPercent"]=2}
,{["jVal"]={5000}
,["id"]=20,["bIsShow"]=false,["oldName"]="金币存储上限",["sDesc"]="晶片储存上限+5000",["nType"]=25,["name"]="战利扩充",["bIsAdd"]=true,["key"]="20",["icon"]="2011",["isPercent"]=2}
,{["jVal"]={0.02}
,["id"]=21,["bIsShow"]=false,["oldName"]="副本战斗伤害",["sDesc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["nType"]=26,["name"]="伤害增幅",["bIsAdd"]=true,["key"]="21",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.05}
,["id"]=22,["bIsShow"]=false,["oldName"]="军演战斗伤害",["sDesc"]="军演战斗伤害增加<color=#FFC432>5%</color>",["nType"]=27,["name"]="军演战斗伤害",["bIsAdd"]=true,["key"]="22",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={5}
,["id"]=23,["bIsShow"]=false,["oldName"]="副本开场能量值",["sDesc"]="战斗开始时，额外增加<color=#FFC432>5能量值</color>",["nType"]=28,["name"]="作战整备",["bIsAdd"]=true,["key"]="23",["icon"]="2011",["isPercent"]=2}
,{["jVal"]={5}
,["id"]=24,["bIsShow"]=false,["oldName"]="军演开场能量值",["sDesc"]="模拟军演中，战斗开始时额外增加5能量值",["nType"]=29,["name"]="演习整备",["bIsAdd"]=true,["key"]="24",["icon"]="2011",["isPercent"]=2}
,{["jVal"]={{10001,5}
}
,["id"]=25,["bIsShow"]=false,["sDesc"]="增加获得物品数量",["oldName"]="增加获得物品数量",["jOpenDups"]={{1101,1102,1103}
,1,1}
,["nType"]=33,["name"]="增加获得物品数量",["bIsAdd"]=false,["key"]="25",["icon"]="2011",["isPercent"]=2}
,{["jVal"]={{10001,2}
}
,["id"]=26,["bIsShow"]=false,["sDesc"]="增加获得物品百分比",["oldName"]="增加获得物品百分比",["jOpenDups"]={{1101,1102,1103}
,1,1}
,["nType"]=34,["name"]="增加获得物品百分比",["bIsAdd"]=false,["key"]="26",["icon"]="2011",["isPercent"]=2}
,{["jVal"]={0.4}
,["id"]=27,["bIsShow"]=false,["oldName"]="存储器经验",["sDesc"]="战斗结算时，解析库额外获得40%技术点",["nType"]=37,["name"]="技术解析",["bIsAdd"]=true,["key"]="27",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={0.3}
,["id"]=28,["bIsShow"]=false,["oldName"]="溢出经验返还",["sDesc"]="战斗结算时，参战角色溢出技术点的30%返还到解析库中",["nType"]=38,["name"]="技术回收",["bIsAdd"]=true,["key"]="28",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={{10003,0.05}
}
,["id"]=29,["bIsShow"]=false,["sDesc"]="每日探索中，【<color=#FFC432>技术解析</color>】关卡额外增加<color=#FFC432>5%</color>技术点产出",["oldName"]="日常本经验掉落加成",["jOpenDups"]={{6201,6202,6203,6204,6205,6206}
,104,501}
,["nType"]=34,["name"]="经验加成",["bIsAdd"]=true,["key"]="29",["icon"]="2011",["isPercent"]=1}
,{["jVal"]={{10001,0.05}
}
,["id"]=30,["bIsShow"]=false,["sDesc"]="每日探索中，【<color=#FFC432>星币开采</color>】关卡额外增加<color=#FFC432>5%</color>星币产出",["oldName"]="日常本金币掉落加成",["jOpenDups"]={{6101,6102,6103,6104,6105,6106}
,103,401}
,["nType"]=34,["name"]="星币加成",["bIsAdd"]=true,["key"]="30",["icon"]="2011",["isPercent"]=1}
}

