_G["CfgPlrAbility"]={{["can_reset"]=true,["type"]=1,["id"]=1,["desc"]="解锁可在战斗中使用的<color=#FFC432>【续行战术】</color>技能组",["oldName"]="复活战术",["cost_num"]=50,["next_id"]={2}
,["key"]="1",["open_lv"]=1,["active_id"]=1003,["name"]="续行战术",["icon"]="203",["pos"]={2,1}
}
,{["can_reset"]=true,["type"]=2,["id"]=2,["prev_id"]={1}
,["key"]="2",["oldName"]="副本开场能量值",["cost_num"]=50,["next_id"]={3}
,["name"]="作战整备1",["open_lv"]=1,["active_id"]=23,["desc"]="战斗开始时，额外增加<color=#FFC432>5能量值</color>",["icon"]="101",["pos"]={2,2}
}
,{["can_reset"]=true,["type"]=2,["id"]=3,["prev_id"]={2}
,["key"]="3",["oldName"]="经验加成",["cost_num"]=50,["next_id"]={4,5,6}
,["name"]="经验加成1",["open_lv"]=1,["active_id"]=29,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>技术点",["icon"]="103",["pos"]={2,3}
}
,{["can_reset"]=true,["type"]=2,["id"]=4,["prev_id"]={3}
,["key"]="4",["oldName"]="副本开场能量值",["cost_num"]=50,["next_id"]={10}
,["name"]="作战整备2",["open_lv"]=1,["active_id"]=23,["desc"]="战斗开始时，额外增加<color=#FFC432>5能量值</color>",["icon"]="101",["pos"]={2,4}
}
,{["can_reset"]=true,["type"]=2,["id"]=5,["prev_id"]={3}
,["key"]="5",["oldName"]="经验加成",["cost_num"]=50,["next_id"]={7}
,["name"]="经验加成2",["open_lv"]=1,["active_id"]=29,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>技术点",["icon"]="103",["pos"]={1,4}
}
,{["can_reset"]=true,["type"]=2,["id"]=6,["prev_id"]={3}
,["key"]="6",["oldName"]="星币加成",["cost_num"]=50,["next_id"]={11}
,["name"]="星币加成1",["open_lv"]=1,["active_id"]=30,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>星币",["icon"]="107",["pos"]={3,4}
}
,{["can_reset"]=true,["type"]=2,["id"]=7,["prev_id"]={5}
,["key"]="7",["oldName"]="副本伤害",["cost_num"]=50,["next_id"]={8}
,["name"]="伤害增幅1",["open_lv"]=1,["active_id"]=21,["desc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["icon"]="106",["pos"]={1,5}
}
,{["can_reset"]=true,["type"]=1,["id"]=8,["prev_id"]={7,10,11}
,["key"]="8",["oldName"]="控条战术",["cost_num"]=50,["next_id"]={9}
,["name"]="机动战术",["open_lv"]=1,["active_id"]=1002,["desc"]="解锁可在战斗中使用的<color=#FFC432>【机动战术】</color>技能组",["icon"]="202",["pos"]={2,6}
}
,{["can_reset"]=true,["type"]=2,["id"]=9,["prev_id"]={8}
,["key"]="9",["oldName"]="星币加成",["cost_num"]=50,["next_id"]={12}
,["name"]="星币加成2",["open_lv"]=1,["active_id"]=30,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>星币",["icon"]="107",["pos"]={2,7}
}
,{["can_reset"]=true,["type"]=2,["id"]=10,["prev_id"]={4}
,["key"]="10",["oldName"]="副本伤害",["cost_num"]=50,["next_id"]={8}
,["name"]="伤害增幅2",["open_lv"]=1,["active_id"]=21,["desc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["icon"]="106",["pos"]={2,5}
}
,{["can_reset"]=true,["type"]=2,["id"]=11,["prev_id"]={6}
,["key"]="11",["oldName"]="副本伤害",["cost_num"]=50,["next_id"]={8}
,["name"]="伤害增幅3",["open_lv"]=1,["active_id"]=21,["desc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["icon"]="106",["pos"]={3,5}
}
,{["can_reset"]=true,["type"]=2,["id"]=12,["prev_id"]={9}
,["key"]="12",["oldName"]="经验加成",["cost_num"]=50,["next_id"]={13}
,["name"]="经验加成3",["open_lv"]=1,["active_id"]=29,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>技术点",["icon"]="103",["pos"]={2,8}
}
,{["can_reset"]=true,["type"]=1,["id"]=13,["prev_id"]={12}
,["key"]="13",["oldName"]="速攻战术",["cost_num"]=50,["next_id"]={14,15,16}
,["name"]="速攻战术",["open_lv"]=1,["active_id"]=1001,["desc"]="解锁可在战斗中使用的<color=#FFC432>【速攻战术】</color>技能组",["icon"]="201",["pos"]={2,9}
}
,{["can_reset"]=true,["type"]=2,["id"]=14,["prev_id"]={13}
,["key"]="14",["oldName"]="副本伤害",["cost_num"]=50,["next_id"]={17}
,["name"]="伤害增幅4",["open_lv"]=1,["active_id"]=21,["desc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["icon"]="106",["pos"]={2,10}
}
,{["can_reset"]=true,["type"]=2,["id"]=15,["prev_id"]={13}
,["key"]="15",["oldName"]="星币加成",["cost_num"]=50,["next_id"]={19}
,["name"]="星币加成3",["open_lv"]=1,["active_id"]=30,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>星币",["icon"]="107",["pos"]={1,10}
}
,{["can_reset"]=true,["type"]=2,["id"]=16,["prev_id"]={13}
,["key"]="16",["oldName"]="经验加成",["cost_num"]=50,["next_id"]={20}
,["name"]="经验加成4",["open_lv"]=1,["active_id"]=29,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>技术点",["icon"]="103",["pos"]={3,10}
}
,{["can_reset"]=true,["type"]=2,["id"]=17,["prev_id"]={14}
,["key"]="17",["oldName"]="星币加成",["cost_num"]=50,["next_id"]={18}
,["name"]="星币加成4",["open_lv"]=1,["active_id"]=30,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>星币",["icon"]="107",["pos"]={2,11}
}
,{["can_reset"]=true,["type"]=1,["id"]=18,["prev_id"]={17}
,["key"]="18",["oldName"]="爆发战术",["cost_num"]=50,["next_id"]={21}
,["name"]="爆发战术",["open_lv"]=1,["active_id"]=1004,["desc"]="解锁可在战斗中使用的<color=#FFC432>【爆发战术】</color>技能组",["icon"]="204",["pos"]={2,12}
}
,{["can_reset"]=true,["type"]=2,["id"]=19,["prev_id"]={15}
,["oldName"]="副本伤害",["key"]="19",["cost_num"]=50,["name"]="伤害增幅5",["open_lv"]=1,["active_id"]=21,["desc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["icon"]="106",["pos"]={1,11}
}
,{["can_reset"]=true,["type"]=2,["id"]=20,["prev_id"]={16}
,["oldName"]="副本伤害",["key"]="20",["cost_num"]=50,["name"]="伤害增幅6",["open_lv"]=1,["active_id"]=21,["desc"]="作战探索中，额外增加<color=#FFC432>2%</color>造成伤害",["icon"]="106",["pos"]={3,11}
}
,{["can_reset"]=true,["type"]=1,["id"]=21,["prev_id"]={18}
,["key"]="21",["oldName"]="削弱战术",["cost_num"]=50,["next_id"]={22,23}
,["name"]="削弱战术",["open_lv"]=1,["active_id"]=1005,["desc"]="解锁可在战斗中使用的<color=#FFC432>【削弱战术】</color>技能组",["icon"]="205",["pos"]={2,13}
}
,{["can_reset"]=true,["type"]=2,["id"]=22,["prev_id"]={21}
,["oldName"]="星币加成",["key"]="22",["cost_num"]=50,["name"]="星币加成5",["open_lv"]=1,["active_id"]=30,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>星币",["icon"]="107",["pos"]={1,14}
}
,{["can_reset"]=true,["type"]=2,["id"]=23,["prev_id"]={21}
,["oldName"]="经验加成",["key"]="23",["cost_num"]=50,["name"]="经验加成5",["open_lv"]=1,["active_id"]=29,["desc"]="作战探索中，额外增加<color=#FFC432>5%</color>技术点",["icon"]="103",["pos"]={3,14}
}
}

