local conf = {
	["filename"] = 'G-GM命令表.xlsx',
	["sheetname"] = 'GM列表',
	["types"] = {
'int','string','string','int','string','string','string'
},
	["names"] = {
'id','type','cmd','num','desc','use','exapmle'
},
	["data"] = {
{'1',	'战斗',	'overFight',	'0',	'一键结束战斗',	'overFight',	'overFight'},
{'2',	'战斗',	'passAll',	'1',	'一键通关',	'passAll 星级',	'passAll 3'},
{'3',	'玩家',	'plrlvl',	'1',	'设置玩家等级',	'plrlvl 等级',	'plrlvl 100'},
{'4',	'卡牌',	'superCard',	'1',	'卡牌满级,满级玩家',	'superCard 卡牌id',	'superCard 10010'},
{'5',	'卡牌',	'fullLvCard',	'1',	'卡牌满级，不改变玩家等级',	'fullLvCard 卡牌id',	'fullLvCard 10010'},
{'6',	'卡牌',	'addAllCard',	'0',	'添加所有卡牌',	'addAllCard',	''},
{'7',	'背包',	'fullItemBag',	'1',	'满背包',	'fullItemBag 物品百分比(1,100] 物品类型(不指定就添加全部类型)',	'fullItemBag 100 2'},
{'8',	'背包',	'cleanItemBag',	'1',	'清空背包',	'cleanItemBag (不删宿舍物品) / cleanItemBag 1 (删除宿舍物品)',	'cleanItemBag'},
{'9',	'邮件',	'mail',	'1',	'给玩家发送邮件',	'mail 邮件配置Id',	'mail 10001'},
{'10',	'邮件',	'rmail',	'2',	'掉落邮件',	'mail 掉落id 次数',	'mail 10001 12'},
{'11',	'邮件',	'gmail',	'1',	'发送全局邮件',	'gmail 邮件配置Id',	'mail 10001'},
{'12',	'邮件',	'gmMail',	'5',	'发送gm邮件',	'gmMail title sendFrom endTime contents rewards',	'gmMail title gm 189898989 hello {{id =11002, num=1, type=2}, {id =1002, num=1, type=3}, {id =2010101, num=1, type=4}}'},
{'13',	'活动',	'openactive',	'1',	'开启活动命令',	'openactive 活动配置id, 当不填写id的时候全部开启',	''},
{'14',	'活动',	'exchagneCode',	'1',	'兑换码序列',	'exchagneCode  0100-0001-AQW9-AQEP-8F7M',	''},
{'15',	'基地',	'buildHp',	'2',	'设置建筑血量百分比',	'cleanItemBag',	'buildHp 50 1001'},
{'16',	'基地',	'resetBuild',	'0',	'重置建筑信息',	'resetBuild',	'resetBuild'},
{'17',	'基地',	'setRoleLv',	'2',	'设置卡牌角色好感度',	'setRoleLv 数值 卡牌配置id(没有id表示设置全部)',	'setRoleLv 99 10010'},
{'18',	'基地',	'setRoleTired',	'2',	'设置角色疲劳值',	'setRoleTired [0, 100] [卡牌配置id](没有id表示设置全部)',	'setRoleTired 33 10010'},
{'19',	'基地',	'reInitEpdnTasks',	'1',	'重置远征任务，可在开启gmPlr 1 之后使用，就不受开启条件限制',	'reInitEpdnTasks',	'reInitEpdnTasks'},
{'20',	'基地',	'buildResetTrade',	'0',	'刷新交易订单',	'buildResetTrade',	'buildResetTrade'},
{'21',	'基地',	'productCenterReward',	'0',	'基地生产中心产出一次（使用后产出重新开始倒计时）',	'productCenterReward',	'productCenterReward'},
{'22',	'基地',	'resetRoleTvTime',	'1',	'清楚角色记录的疲劳计算时间缓存(没角色id表示全部)',	'resetRoleTvTime [角色cfgid]',	'resetRoleTvTime'},
{'23',	'基地',	'dormTheme',	'2',	'根据主题增删宿舍家具',	'dormTheme [1:添加/-1:删除] 主题id',	'dormTheme 1 1001'},
{'24',	'军演',	'armyReset',	'1',	'重置军演信息',	'armyReset 增减的分数 可对战次数 已购买对战次数',	'armyReset 1 5 0'},
{'25',	'装备',	'superEquip',	'0',	'装备满级',	'superEquip',	''},
{'26',	'装备',	'addEquip',	'5',	'添加装备',	'addEquip 装备id 数量 技能1 技能2 技能3',	''},
{'27',	'装备',	'addAllEquip',	'1',	'添加 maxCnt 件不同装备',	'addAllEquip maxCnt数量',	''},
{'28',	'装备',	'sellAllEquip',	'0',	'销售所有装备, 包括上锁与装备的',	'sellAllEquip',	'sellAllEquip'},
{'29',	'卡牌',	'addTestCard',	'0',	'添加配置表gm无法获取的卡牌',	'addTestCard',	''},
{'30',	'卡牌',	'addcard',	'1',	'添加卡牌',	'addcard 卡牌id',	''},
{'31',	'卡牌',	'cardHot',	'1',	'设置所有卡牌热值',	'cardHot 热值',	''},
{'32',	'卡牌',	'storeExp',	'1',	'增减存储经验',	'storeExp 数值',	''},
{'33',	'卡牌',	'cleanCard',	'0',	'当没有指定id时候，清空没使用的卡牌',	'cleanCard [卡牌id, -1表全删] [是否删除锁定,填1]',	'cleanCard -1 1'},
{'34',	'卡牌',	'testCardPool',	'3',	'测试十连抽',	'testCardPool 卡池id 十连抽次数 测试品质',	'testCardPool 1003 5 3'},
{'35',	'卡牌',	'createCardCntReset',	'0',	'重置必掉落抽卡次数计数',	'createCardCntReset',	'createCardCntReset'},
{'36',	'卡牌',	'resetCardRoles',	'0',	'重置所有角色',	'resetCardRoles',	'resetCardRoles'},
{'37',	'卡牌',	'resetCardCreateLog',	'0',	'重置抽卡信息',	'resetCardCreateLog',	'resetCardCreateLog'},
{'38',	'玩家',	'plrexp',	'1',	'添加玩家经验',	'plrexp 经验',	'plrexp 100'},
{'39',	'玩家',	'money',	'2',	'改变金钱',	'money 钻石数量 金币数量 （正数为添加，负数为减少， 0 为不变）',	'money 100 1000 （100钻石，1000金币）'},
{'40',	'玩家',	'gmPlr',	'1',	'gm player, 设置GM玩家特权',	'gmPlr 1[时间秒数，没有表示关闭]',	'gmPlr 1：开启/gmPlr：关闭'},
{'41',	'玩家',	'accNumer',	'2',	'设置玩家防沉迷信息',	'accNumer 440106200303050920 大爷',	'accNumer 身份证号 姓名'},
{'42',	'玩家',	'ablilitys',	'0',	'开启所有能力',	'ablilitys',	''},
{'43',	'玩家',	'skillGroup',	'0',	'开启所有技能组',	'skillGroup',	''},
{'44',	'玩家',	'skillGroupReset',	'0',	'重置所有能力，会重置buf与技能组',	'skillGroupReset',	'skillGroupReset'},
{'45',	'玩家',	'lbExpTime',	'1',	'设置生活buf多久过期',	'lbExpTime 多久之后过期(秒)',	'lbExpTime 30'},
{'46',	'玩家',	'setMemberLeftDay',	'2',	'设置会员剩余天数',	'setMemberLeftDay 会员物品id 剩余5天数',	'setMemberLeftDay 10030 5'},
{'47',	'玩家',	'setPlrNum',	'2',	'设置玩家数值',	'setPlrNum 字段值 数值',	'setPlrNum hot 0'},
{'48',	'玩家',	'setPlrMixNum',	'2',	'设置玩家Mix数值',	'setPlrMixNum 字段值 数值',	'setPlrMixNum hotBuyCnt 0'},
{'49',	'玩家',	'clearBuySkin',	'0',	'清空已购买的皮肤和购买记录',	'clearBuySkin',	'clearBuySkin'},
{'50',	'玩家',	'addInlinePayRet',	'3',	'写入内陆支付返还',	'addInlinePayRet 充值金额 月卡数量 是否登录[0:需要登录返还/1：马上返还]',	'addInlinePayRet 10 1 1'},
{'51',	'战斗',	'passgate',	'2',	'通过某一关',	'passgate 关卡id 星数',	'passgate 1105 3'},
{'52',	'战斗',	'EnterFight',	'1',	'进入战斗',	'EnterFight 关卡id',	'EnterFight 101011'},
{'53',	'战斗',	'guildFightTest',	'0',	'进入工会战测试多人房间',	'guildFightTest',	'guildFightTest'},
{'54',	'战斗',	'tbFinish',	'1',	'Team boss finish 完结所在的组队boss房间,',	'tbFinish 1[胜利]/0[失败]',	'tbFinish 1'},
{'55',	'战斗',	'tbFightOver',	'0',	'Team boss fight over 直接完结战斗,',	'tbFightOver 1[击败boss/不输入默认不击败]',	'tbFightOver'},
{'56',	'战斗',	'tower',	'0',	'重置爬塔奖励',	'tower',	'tower'},
{'57',	'战斗',	'delStory',	'0',	'删除剧情',	'delStory',	'delStory'},
{'58',	'世界boss',	'settp',	'1',	'设置tp值',	'settp tp值',	'settp 3'},
{'59',	'掉落',	'reward',	'1',	'掉落',	'reward 配置表id',	''},
{'60',	'掉落',	'showRewardCfg',	'1',	'前端显示掉落配置',	'showRewardCfg 配置表id',	'showRewardCfg 1001'},
{'61',	'背包',	'additem',	'3',	'添加物品',	'additem 物品id 数量 [自动使用]',	'additem 10010 23 1'},
{'62',	'商店',	'shop',	'3',	'shop 购买记录id(和配置表id一样) 操作类型 操作值',	'shop 11001 1 0 取消折扣/shop 11001 1 1 开始折扣/shop 11001 2  设置记录即将重置',	''},
{'63',	'任务',	'finishTasks',	'3',	'完成所有任务[1:主线,2:支线,3:日常,4:每周,5:活动,6:长期副本爬塔,7:短期副本爬塔]',	'finishTasks 任务类型[不填表示全部] cfgId[0:表示类型全部] 完成次数',	''},
{'64',	'任务',	'resetTask',	'1',	'重置任务',	'resetTask 任务类型[不填表示全部]',	'resetTask'},
{'65',	'控制',	'time',	'1',	'设定服务器事件',	'time 2019-10-13-11:40:30',	''},
{'66',	'控制',	'reload',	'1',	'热更当前游戏服',	'reload [文件名，文件名忽略则热更包含配置表在内的所有默认文件]',	'reload character.Player'},
{'67',	'控制',	'tips',	'1',	'显示提示信息',	'tips 提示id',	'tips 205'},
{'68',	'控制',	'changeSvr',	'1',	'切换游戏服',	'changeSvr 服务器id',	'changeSvr 101'},
{'69',	'战场',	'resetFieldBossCount',	'0',	'重置激战前线挑战次数',	'resetFieldBossCount',	'resetFieldBossCount'},
{'70',	'战场',	'setFieldCount',	'4',	'设置局部战场的敌人数量',	'setFieldCount战场系统关卡id 初始敌人人数 总敌人人数',	'setFieldCount?11001?4?6'},
{'71',	'战场',	'resetFieldBoss',	'1',	'重置激战前线的boss血量',	'resetFieldBossCount?boss血量（血量为0或者不填，默认最大值）',	'resetFieldBossCount?10000'},
{'72',	'七日',	'sevenTaskOpenNewDay',	'0',	'开启新一天的七日任务',	'sevenTaskOpenNewDay',	'sevenTaskOpenNewDay'},
{'73',	'勘测',	'resetExploration',	'0',	'重置测绘记录',	'resetExploration',	'resetExploration'},
{'74',	'购买',	'recharge',	'1',	'模拟充值',	'recharge id[CfgCommodity表的id]',	'recharge 40001'},
{'75',	'回归',	'setReturnPlr',	'1',	'设置回归玩家',	'setReturnPlr 回归类型( 1短期回归玩家，2长期回归玩家)',	'setReturnPlr 1'},
{'76',	'战斗',	'setRogueBuff',	'1',	'设置乱序演习当前回合词条',	'setRogueBuff buffid',	'setRogueBuff 15001'},
{'77',	'乱序',	'refreshRogueBuff',	'0',	'重新随机当前乱序演习随机词条',	'refreshRogueBuff (需要保存进度退出界面再重新进入选择buff界面)',	'refreshRogueBuff'},
{'78',	'乱序',	'setRogueDuplicate',	'1',	'乱序选怪物界面，固定选择某个怪物id',	'setRogueDuplicate 关卡ID (在翻怪物卡牌前输入，输入完需保存进度退出界面再重新进入)',	'setRogueDuplicate 40001'},
{'79',	'重置道具池',	'resetItemPool',	'1',	'重置道具池',	'resetItemPool 道具池ID（没填则默认所有道具池重置）',	'resetItemPool 1001'},
{'80',	'乱序',	'passRogue',	'1',	'通关乱序演习关卡组,不填id全部通关',	'passRogue 关卡组ID(没填则默认所有乱序关卡)',	'passRogue 15001'},
},
}
--cfgGmCmdList = conf
return conf
