local conf = {
	["filename"] = 's-声音.xlsx',
	["sheetname"] = '剧情音效',
	["types"] = {
'int','string','string','string','int'
},
	["names"] = {
'id','key','cue_sheet','cue_name','loop'
},
	["data"] = {
{'10001',	'short_click',	'plot_effect/plot_effect.acb',	'short_click',	''},
{'10002',	'short_alert_loop',	'plot_effect/plot_effect.acb',	'short_alert_loop',	'1'},
{'10003',	'short_alert',	'plot_effect/plot_effect.acb',	'short_alert',	''},
{'10004',	'short_pace',	'plot_effect/plot_effect.acb',	'short_pace',	''},
{'10005',	'short_slash',	'plot_effect/plot_effect.acb',	'short_slash',	''},
{'10006',	'short_incised',	'plot_effect/plot_effect.acb',	'short_incised',	''},
{'10007',	'short_clash',	'plot_effect/plot_effect.acb',	'short_clash',	''},
{'10008',	'short_bump',	'plot_effect/plot_effect.acb',	'short_bump',	''},
{'10009',	'short_slip',	'plot_effect/plot_effect.acb',	'short_slip',	''},
{'10010',	'short_Noisy',	'plot_effect/plot_effect.acb',	'short_Noisy',	''},
{'10011',	'short_monster',	'plot_effect/plot_effect.acb',	'short_monster',	''},
{'10012',	'short_laser',	'plot_effect/plot_effect.acb',	'short_laser',	''},
{'10013',	'short_cannon',	'plot_effect/plot_effect.acb',	'short_cannon',	''},
{'10014',	'short_thunder',	'plot_effect/plot_effect.acb',	'short_thunder',	''},
{'10015',	'short_engine',	'plot_effect/plot_effect.acb',	'short_engine',	''},
{'10016',	'short_keyboard_loop',	'plot_effect/plot_effect.acb',	'short_keyboard_loop',	'1'},
{'10017',	'short_keyboard',	'plot_effect/plot_effect.acb',	'short_keyboard',	''},
{'10018',	'short_shoot',	'plot_effect/plot_effect.acb',	'short_shoot',	''},
{'10019',	'short_boom',	'plot_effect/plot_effect.acb',	'short_boom',	''},
{'10020',	'short_earthquake',	'plot_effect/plot_effect.acb',	'short_earthquake',	''},
{'10021',	'short_Missile',	'plot_effect/plot_effect.acb',	'short_Missile',	''},
{'10022',	'short_spacejump',	'plot_effect/plot_effect.acb',	'short_spacejump',	''},
{'10023',	'short_run',	'plot_effect/plot_effect.acb',	'short_run',	''},
{'10024',	'short_launch',	'plot_effect/plot_effect.acb',	'short_launch',	''},
{'10025',	'short_landing',	'plot_effect/plot_effect.acb',	'short_landing',	''},
{'10026',	'short_search',	'plot_effect/plot_effect.acb',	'short_search',	''},
{'10027',	'short_communication',	'plot_effect/plot_effect.acb',	'short_communication',	''},
{'10028',	'short_door',	'plot_effect/plot_effect.acb',	'short_door',	''},
{'10029',	'short_quickrun',	'plot_effect/plot_effect.acb',	'short_quickrun',	''},
{'10030',	'short_moving',	'plot_effect/plot_effect.acb',	'short_moving',	''},
{'10031',	'short_bang',	'plot_effect/plot_effect.acb',	'short_bang',	''},
{'10032',	'amb_burning_loop',	'plot_effect/plot_effect.acb',	'amb_burning_loop',	'1'},
{'10033',	'amb_burning',	'plot_effect/plot_effect.acb',	'amb_burning',	''},
{'10034',	'amb_fire_loop',	'plot_effect/plot_effect.acb',	'amb_fire_loop',	'1'},
{'10035',	'amb_fire',	'plot_effect/plot_effect.acb',	'amb_fire',	''},
{'10036',	'amb_rain_loop',	'plot_effect/plot_effect.acb',	'amb_rain_loop',	'1'},
{'10037',	'amb_rain',	'plot_effect/plot_effect.acb',	'amb_rain',	''},
{'10038',	'amb_thunder_loop',	'plot_effect/plot_effect.acb',	'amb_thunder_loop',	'1'},
{'10039',	'amb_thunder',	'plot_effect/plot_effect.acb',	'amb_thunder',	''},
{'10040',	'amb_lighting',	'plot_effect/plot_effect.acb',	'amb_lighting',	''},
{'10041',	'amb_echnology_loop',	'plot_effect/plot_effect.acb',	'amb_echnology_loop',	'1'},
{'10042',	'amb_echnology',	'plot_effect/plot_effect.acb',	'amb_echnology',	''},
{'10043',	'amb_factory_loop',	'plot_effect/plot_effect.acb',	'amb_factory_loop',	'1'},
{'10044',	'amb_factory',	'plot_effect/plot_effect.acb',	'amb_factory',	''},
{'10045',	'amb_snow_loop',	'plot_effect/plot_effect.acb',	'amb_snow_loop',	'1'},
{'10046',	'amb_snow',	'plot_effect/plot_effect.acb',	'amb_snow',	''},
{'10047',	'amb_breeze_loop',	'plot_effect/plot_effect.acb',	'amb_breeze_loop',	'1'},
{'10048',	'amb_breeze',	'plot_effect/plot_effect.acb',	'amb_breeze',	''},
{'10049',	'amb_wind_loop',	'plot_effect/plot_effect.acb',	'amb_wind_loop',	'1'},
{'10050',	'amb_wind',	'plot_effect/plot_effect.acb',	'amb_wind',	''},
{'10051',	'amb_storm_loop',	'plot_effect/plot_effect.acb',	'amb_storm_loop',	'1'},
{'10052',	'amb_storm',	'plot_effect/plot_effect.acb',	'amb_storm',	''},
{'10053',	'amb_forest_loop',	'plot_effect/plot_effect.acb',	'amb_forest_loop',	'1'},
{'10054',	'amb_forest',	'plot_effect/plot_effect.acb',	'amb_forest',	''},
{'10055',	'short_sixgun',	'plot_effect/plot_effect.acb',	'short_sixgun',	''},
{'10056',	'amb_Radio_wave_loop',	'plot_effect/plot_effect.acb',	'amb_Radio_wave_loop',	''},
{'10057',	'ticking_1s',	'plot_effect/plot_effect.acb',	'ticking_1s',	''},
{'10058',	'ticking_4s',	'plot_effect/plot_effect.acb',	'ticking_4s',	''},
{'10059',	'ticking_12s',	'plot_effect/plot_effect.acb',	'ticking_12s',	''},
{'10060',	'ticking_12s_loop',	'plot_effect/plot_effect.acb',	'ticking_12s_loop',	'1'},
{'10061',	'sea_wave',	'plot_effect/plot_effect.acb',	'sea_wave',	''},
{'10062',	'sea_wave_loop',	'plot_effect/plot_effect.acb',	'sea_wave_loop',	'1'},
{'10063',	'Signal_loss_1s',	'plot_effect/plot_effect.acb',	'Signal_loss_1s',	''},
{'10064',	'Signal_loss_loop',	'plot_effect/plot_effect.acb',	'Signal_loss_loop',	'1'},
{'10065',	'bubble',	'plot_effect/plot_effect.acb',	'bubble',	''},
{'10066',	'droplet',	'plot_effect/plot_effect.acb',	'droplet',	''},
{'10067',	'droplet_loop',	'plot_effect/plot_effect.acb',	'droplet_loop',	'1'},
{'10068',	'knock_slow',	'plot_effect/plot_effect.acb',	'knock_slow',	''},
{'10069',	'knock_fast',	'plot_effect/plot_effect.acb',	'knock_fast',	''},
},
}
--cfgPlotSound = conf
return conf
