_G["PlotSound"]={[10001]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_click",["cue_name"]="short_click",["id"]=10001}
,[10002]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="short_alert_loop",["cue_name"]="short_alert_loop",["id"]=10002}
,[10003]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_alert",["cue_name"]="short_alert",["id"]=10003}
,[10004]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_pace",["cue_name"]="short_pace",["id"]=10004}
,[10005]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_slash",["cue_name"]="short_slash",["id"]=10005}
,[10006]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_incised",["cue_name"]="short_incised",["id"]=10006}
,[10007]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_clash",["cue_name"]="short_clash",["id"]=10007}
,[10008]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_bump",["cue_name"]="short_bump",["id"]=10008}
,[10009]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_slip",["cue_name"]="short_slip",["id"]=10009}
,[10010]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_Noisy",["cue_name"]="short_Noisy",["id"]=10010}
,[10011]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_monster",["cue_name"]="short_monster",["id"]=10011}
,[10012]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_laser",["cue_name"]="short_laser",["id"]=10012}
,[10013]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_cannon",["cue_name"]="short_cannon",["id"]=10013}
,[10014]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_thunder",["cue_name"]="short_thunder",["id"]=10014}
,[10015]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_engine",["cue_name"]="short_engine",["id"]=10015}
,[10016]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="short_keyboard_loop",["cue_name"]="short_keyboard_loop",["id"]=10016}
,[10017]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_keyboard",["cue_name"]="short_keyboard",["id"]=10017}
,[10018]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_shoot",["cue_name"]="short_shoot",["id"]=10018}
,[10019]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_boom",["cue_name"]="short_boom",["id"]=10019}
,[10020]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_earthquake",["cue_name"]="short_earthquake",["id"]=10020}
,[10021]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_Missile",["cue_name"]="short_Missile",["id"]=10021}
,[10022]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_spacejump",["cue_name"]="short_spacejump",["id"]=10022}
,[10023]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_run",["cue_name"]="short_run",["id"]=10023}
,[10024]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_launch",["cue_name"]="short_launch",["id"]=10024}
,[10025]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_landing",["cue_name"]="short_landing",["id"]=10025}
,[10026]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_search",["cue_name"]="short_search",["id"]=10026}
,[10027]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_communication",["cue_name"]="short_communication",["id"]=10027}
,[10028]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_door",["cue_name"]="short_door",["id"]=10028}
,[10029]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_quickrun",["cue_name"]="short_quickrun",["id"]=10029}
,[10030]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_moving",["cue_name"]="short_moving",["id"]=10030}
,[10031]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_bang",["cue_name"]="short_bang",["id"]=10031}
,[10032]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_burning_loop",["cue_name"]="amb_burning_loop",["id"]=10032}
,[10033]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_burning",["cue_name"]="amb_burning",["id"]=10033}
,[10034]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_fire_loop",["cue_name"]="amb_fire_loop",["id"]=10034}
,[10035]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_fire",["cue_name"]="amb_fire",["id"]=10035}
,[10036]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_rain_loop",["cue_name"]="amb_rain_loop",["id"]=10036}
,[10037]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_rain",["cue_name"]="amb_rain",["id"]=10037}
,[10038]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_thunder_loop",["cue_name"]="amb_thunder_loop",["id"]=10038}
,[10039]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_thunder",["cue_name"]="amb_thunder",["id"]=10039}
,[10040]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_lighting",["cue_name"]="amb_lighting",["id"]=10040}
,[10041]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_echnology_loop",["cue_name"]="amb_echnology_loop",["id"]=10041}
,[10042]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_echnology",["cue_name"]="amb_echnology",["id"]=10042}
,[10043]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_factory_loop",["cue_name"]="amb_factory_loop",["id"]=10043}
,[10044]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_factory",["cue_name"]="amb_factory",["id"]=10044}
,[10045]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_snow_loop",["cue_name"]="amb_snow_loop",["id"]=10045}
,[10046]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_snow",["cue_name"]="amb_snow",["id"]=10046}
,[10047]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_breeze_loop",["cue_name"]="amb_breeze_loop",["id"]=10047}
,[10048]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_breeze",["cue_name"]="amb_breeze",["id"]=10048}
,[10049]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_wind_loop",["cue_name"]="amb_wind_loop",["id"]=10049}
,[10050]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_wind",["cue_name"]="amb_wind",["id"]=10050}
,[10051]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_storm_loop",["cue_name"]="amb_storm_loop",["id"]=10051}
,[10052]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_storm",["cue_name"]="amb_storm",["id"]=10052}
,[10053]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="amb_forest_loop",["cue_name"]="amb_forest_loop",["id"]=10053}
,[10054]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_forest",["cue_name"]="amb_forest",["id"]=10054}
,[10055]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="short_sixgun",["cue_name"]="short_sixgun",["id"]=10055}
,[10056]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="amb_Radio_wave_loop",["cue_name"]="amb_Radio_wave_loop",["id"]=10056}
,[10057]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="ticking_1s",["cue_name"]="ticking_1s",["id"]=10057}
,[10058]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="ticking_4s",["cue_name"]="ticking_4s",["id"]=10058}
,[10059]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="ticking_12s",["cue_name"]="ticking_12s",["id"]=10059}
,[10060]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="ticking_12s_loop",["cue_name"]="ticking_12s_loop",["id"]=10060}
,[10061]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="sea_wave",["cue_name"]="sea_wave",["id"]=10061}
,[10062]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="sea_wave_loop",["cue_name"]="sea_wave_loop",["id"]=10062}
,[10063]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="Signal_loss_1s",["cue_name"]="Signal_loss_1s",["id"]=10063}
,[10064]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="Signal_loss_loop",["cue_name"]="Signal_loss_loop",["id"]=10064}
,[10065]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="bubble",["cue_name"]="bubble",["id"]=10065}
,[10066]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="droplet",["cue_name"]="droplet",["id"]=10066}
,[10067]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="droplet_loop",["cue_name"]="droplet_loop",["id"]=10067}
,[10068]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="knock_slow",["cue_name"]="knock_slow",["id"]=10068}
,[10069]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="knock_fast",["cue_name"]="knock_fast",["id"]=10069}
,[10070]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="Fireworks_Set",["cue_name"]="Fireworks_Set",["id"]=10070}
,[10071]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="Fireworks_Boom",["cue_name"]="Fireworks_Boom",["id"]=10071}
,[10072]={["cue_sheet"]="plot_effect/plot_effect.acb",["loop"]=1,["key"]="Fireworks_Loop",["cue_name"]="Fireworks_Loop",["id"]=10072}
,[10073]={["cue_sheet"]="plot_effect/plot_effect.acb",["key"]="Blanket",["cue_name"]="Blanket",["id"]=10073}
}

