_G["PlotVideo"]={{["loop"]=1,["name"]="plot/plot_burn1",["id"]=1,["time"]=1,["key"]="1"}
,{["name"]="plot/plot_explode1",["id"]=2,["time"]=1,["key"]="2"}
,{["name"]="plot/plot_hit1",["id"]=3,["time"]=1,["key"]="3"}
,{["name"]="plot/plot_hit2",["id"]=4,["time"]=1,["key"]="4"}
,{["loop"]=1,["name"]="plot/plot_rain1",["id"]=5,["time"]=1,["key"]="5"}
,{["loop"]=1,["name"]="plot/plot_rain2",["id"]=6,["time"]=1,["key"]="6"}
,{["loop"]=1,["name"]="plot/plot_through1",["id"]=7,["time"]=1,["key"]="7"}
,{["name"]="plot/plot_explode2",["id"]=8,["time"]=1,["key"]="8"}
,{["loop"]=1,["name"]="plot/plot_warning1",["id"]=9,["time"]=1,["key"]="9"}
,{["name"]="plot/plot_warning2",["id"]=10,["time"]=1,["key"]="10"}
,{["loop"]=1,["name"]="plot/plot_camera",["id"]=11,["time"]=1,["key"]="11"}
,{["name"]="plot/plot_camera_end",["id"]=12,["time"]=1,["key"]="12"}
,{["name"]="plot2/plot_misc1",["id"]=13,["time"]=1,["key"]="13"}
,{["loop"]=1,["name"]="plot/plot_line1",["id"]=14,["time"]=1,["key"]="14"}
,{["loop"]=1,["name"]="plot/plot_line2",["id"]=15,["time"]=1,["key"]="15"}
,{["loop"]=1,["name"]="plot/plot_line3",["id"]=16,["time"]=1,["key"]="16"}
,{["name"]="plot2/plot_cutsence",["id"]=17,["time"]=1,["key"]="17"}
}

