name: Check file changes
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
    inputs:
      force_check:
        description: 'Force check hash to be true'
        required: false
        default: 'false'
      send_mail:
        description: 'Send mail'
        required: false
        default: 'true'

jobs:
  check-file:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: ['android', 'ios']
        include:
          - platform: 'android'
            url: 'https://cdn.megagamelog.com/cross/release/android/curr/Custom/luascripts'
            filename: 'lua_android'
          - platform: 'ios'
            url: 'https://cdn.megagamelog.com/cross/release/ios/curr_new/Custom/luascripts'
            filename: 'lua_ios'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      if: steps.check-hash.outputs.changed == 'true'
      with:
        persist-credentials: false

    - name: Download file
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        curl -L -o ${{ matrix.filename }} "${{ matrix.url }}"

    - name: Calculate hash
      id: calc-hash
      shell: bash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        echo "::set-output name=hash::$(sha256sum ${{ matrix.filename }} | awk '{ print $1 }')"

    - name: Save hash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        echo "${{ steps.calc-hash.outputs.hash }}" > D:/a/CrossCoreLuascripts/CrossCoreLuascripts/new-hash.txt

    - name: Check hash
      id: check-hash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
        HASH: ${{ steps.calc-hash.outputs.hash }}
      run: |
        cd $WORKSPACE_PATH
        if ('${{ github.event.inputs.force_check }}' -eq 'true') {
          mv D:/a/CrossCoreLuascripts/CrossCoreLuascripts/new-hash.txt D:/a/CrossCoreLuascripts/CrossCoreLuascripts/${{ matrix.filename }}-hash.txt
          echo "::set-output name=changed::true"
        } else {
          echo "Old hash: $(Get-Content D:/a/CrossCoreLuascripts/CrossCoreLuascripts/${{ matrix.filename }}-hash.txt)"
          echo "New hash: ${env:HASH}"
          if ((Get-Content D:/a/CrossCoreLuascripts/CrossCoreLuascripts/${{ matrix.filename }}-hash.txt) -ne "${env:HASH}") {
            mv D:/a/CrossCoreLuascripts/CrossCoreLuascripts/new-hash.txt D:/a/CrossCoreLuascripts/CrossCoreLuascripts/${{ matrix.filename }}-hash.txt
            echo "::set-output name=changed::true"
          } else {
            echo "::set-output name=changed::false"
          }
        }      

    - name: Unpack and Push
      if: steps.check-hash.outputs.changed == 'true'
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        curl -L -o studio.zip https://github.com/RazTools/Studio/releases/download/v1.00.00/net7.0-windows.zip
        Expand-Archive -Path studio.zip -DestinationPath studio
        git clone "https://${{ secrets.MY_TOKEN }}@github.com/AXiX-official/CrossCore-Auto-Lua.git" D:/a/CrossCoreLuascripts/tool
        python D:/a/CrossCoreLuascripts/tool/decrypt.py "${{ matrix.filename }}"
        mkdir lua
        studio/AssetStudioCLI ${{ matrix.filename }}_decrypt lua --game Normal --silent
        python D:/a/CrossCoreLuascripts/tool/sortFile.py lua/TextAsset D:/a/CrossCoreLuascripts/CrossCoreLuascripts/${{ matrix.platform }} D:/a/CrossCoreLuascripts/tool/structure.json

    - name: Generate commit message
      if: steps.check-hash.outputs.changed == 'true'
      id: commit-message
      shell: bash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        svnVersion=$(grep -o 'g_svnVersion = "[0-9]*' "$WORKSPACE_PATH/${{ matrix.platform }}/SvnVersion.lua" | grep -o '[0-9]*')
        date=$(date +"%Y/%m/%d")
        echo "::set-output name=message::[${date}]-${svnVersion}"

    - name: Commit changes
      if: steps.check-hash.outputs.changed == 'true'
      run: |
        Set-Location -Path D:/a/CrossCoreLuascripts/CrossCoreLuascripts/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ matrix.platform }}
        git add ${{ matrix.platform }}-hash.txt
        git commit -am "${{ steps.commit-message.outputs.message }}" || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Generate cfg vesion
      if: matrix.platform == 'android' && steps.check-hash.outputs.changed == 'true'
      id: cfg-version
      shell: bash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        svnVersion=$(grep -o 'g_svnVersion = "[0-9]*' "$WORKSPACE_PATH/${{ matrix.platform }}/SvnVersion.lua" | grep -o '[0-9]*')
        date=$(date +"%Y%m%d")
        echo "::set-output name=version::${date}-${svnVersion}"

    - name: Step for Android
      if: matrix.platform == 'android' && steps.check-hash.outputs.changed == 'true' && ${{ github.event.inputs.send_mail == 'true'}}
      id: step-android
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        pip install -r D:/a/CrossCoreLuascripts/tool/requirements.txt
        python D:/a/CrossCoreLuascripts/tool/2csv.py lua
        Compress-Archive -Path D:/a/CrossCoreLuascripts/CrossCoreLuascripts/android/cfg -DestinationPath "D:/a/CrossCoreLuascripts/CrossCoreLuascripts/cfg${{ steps.cfg-version.outputs.version }}.zip"
        echo "::set-output name=packed::true"

    - name: Send mail
      if: steps.step-android.outputs.packed == 'true' && ${{ github.event.inputs.send_mail == 'true'}} 
      uses: dawidd6/action-send-mail@v2
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: 交错战线CFG文件更新
        to: ${{ secrets.RECIPIENTS }}
        from: ${{ secrets.GMAIL_USERNAME }}
        body: "cfg${{ steps.cfg-version.outputs.version }}.zip"
        attachments: D:/a/CrossCoreLuascripts/CrossCoreLuascripts/cfg${{ steps.cfg-version.outputs.version }}.zip