name: Check file changes
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
    inputs:
      force_check:
        description: 'Force check hash to be true'
        required: false
        default: 'false'

jobs:
  check-file:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: ['android', 'ios']
        include:
          - platform: 'android'
            url: 'https://cdn.megagamelog.com/cross/release/android/curr/Custom/luascripts'
            filename: 'lua_android'
          - platform: 'ios'
            url: 'https://cdn.megagamelog.com/cross/release/ios/curr_new/Custom/luascripts'
            filename: 'lua_ios'
    steps:
    - name: Download file
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        cd ..
        curl -L -o ${{ matrix.filename }} "${{ matrix.url }}"

    - name: Calculate hash
      id: calc-hash
      shell: bash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        cd ..
        echo "::set-output name=hash::$(sha256sum ${{ matrix.filename }} | awk '{ print $1 }')"

    - name: Save hash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        cd ..
        echo "${{ steps.calc-hash.outputs.hash }}" > new-hash.txt

    - name: Download old hash
      if: ${{ github.event.inputs.force_check == 'false'}} 
      uses: actions/download-artifact@v2
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      with:
        name: hash-${{ matrix.platform }}
        path: ${{ github.workspace }}/../old-hash.txt

    - name: Check hash
      id: check-hash
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        cd ..
        if ('${{ github.event.inputs.force_check }}' -eq 'true') {
          echo "::set-output name=changed::true"
        } else {
          echo "Old hash: $(Get-Content old-hash.txt)"
          echo "New hash: ${env:HASH}"
          if ((Get-Content old-hash.txt) -ne "${env:HASH}") {
            echo "::set-output name=changed::true"
          } else {
            echo "::set-output name=changed::false"
          }
        }
      env:
        HASH: ${{ steps.calc-hash.outputs.hash }}

    - name: Upload new hash
      if: steps.check-hash.outputs.changed == 'true'
      uses: actions/upload-artifact@v2
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      with:
        name: hash-${{ matrix.platform }}
        path: ${{ github.workspace }}/../new-hash.txt

    - name: Checkout code
      uses: actions/checkout@v2
      if: steps.check-hash.outputs.changed == 'true'

    - name: Unpack and Push
      if: steps.check-hash.outputs.changed == 'true'
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        cd ..
        curl -L -o studio.zip https://github.com/RazTools/Studio/releases/download/v1.00.00/net7.0-windows.zip
        Expand-Archive -Path studio.zip -DestinationPath studio
        git clone "https://${{ secrets.MY_TOKEN }}@github.com/AXiX-official/CrossCore-Auto-Lua.git" tool
        python tool/decrypt.py "${{ matrix.filename }}"
        mkdir lua
        studio/AssetStudioCLI "${{ matrix.filename }}_decrypt" lua --game Normal
        python tool/sortFile.py lua "CrossCoreLuascripts/CrossCore-Luascripts/${{ matrix.platform }}" tool/structure.json

    - name: Generate commit message
      if: steps.check-hash.outputs.changed == 'true'
      id: commit-message
      shell: pwsh
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        $svnVersion = Select-String -Path "${{ matrix.platform }}/SvnVersion.lua" -Pattern 'g_svnVersion = "(\d+)"' | % { $_.Matches.Groups[1].Value }
        $date = Get-Date -Format "yyyy/MM/dd"
        echo "::set-output name=message::[${date}]-${svnVersion}"

    - name: Commit changes
      if: steps.check-hash.outputs.changed == 'true'
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ matrix.platform }}
        git commit -am "${{ steps.commit-message.outputs.message }}"
        git push

    - name: Step for Android
      if: matrix.platform == 'android' && steps.check-hash.outputs.changed == 'true'
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      run: |
        cd $WORKSPACE_PATH
        cd ..
        pip install -r tool/requirements.txt
        python tool/2csv.py lua
        Compress-Archive -Path cfg -DestinationPath "cfg${{ steps.commit-message.outputs.message }}.zip"
        echo "::set-output name=packed::true"

    - name: Send mail
      if: steps.check-hash.outputs.changed == 'true'
      uses: dawidd6/action-send-mail@v2
      env:
        WORKSPACE_PATH: ${{ github.workspace }}
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: 交错战线CFG文件更新
        to: ${{ secrets.RECIPIENTS }}
        from: ${{ secrets.GMAIL_USERNAME }}
        body: "cfg${{ steps.commit-message.outputs.message }}.zip"
        attachments: ${{ github.workspace }}/../cfg${{ steps.commit-message.outputs.message }}.zip